# Generated by Django 6.1.1 on 2026-09-22 15:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dojos', '0001_initial'),
        ('pathways', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('category', models.CharField(choices=[('attendance', 'Attendance'), ('skill', 'Skill')], max_length=20)),
                ('criteria', models.CharField(blank=True, default='', help_text='e.g. "Visited the dojo 10 times."', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('places', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326)),
                ('venue_name', models.CharField(blank=True, default='', help_text='e.g. "Ghent Public Library"', max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('what_to_bring', models.TextField(blank=True, default='')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojos.dojo')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='dojos.mentor')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_list', models.BooleanField()),
                ('position', models.IntegerField()),
                ('attended', models.BooleanField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.participant')),
                ('pathway', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registrations', to='pathways.pathway')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='participants',
            field=models.ManyToManyField(through='events.Registration', to='accounts.participant'),
        ),
        migrations.CreateModel(
            name='ParticipantAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateField(blank=True, help_text='Blank if still in progress.', null=True)),
                ('progress_current', models.PositiveIntegerField(blank=True, null=True)),
                ('progress_total', models.PositiveIntegerField(blank=True, null=True)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participant_awards', to='events.award')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards', to='accounts.participant')),
            ],
            options={
                'unique_together': {('participant', 'award')},
            },
        ),
    ]
