# Generated by Django 6.1.1 on 2026-09-24 10:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_initial'),
        ('dojos', '0001_initial'),
        ('pathways', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Yellow belt".', max_length=100)),
                ('level', models.PositiveSmallIntegerField(help_text='Order on the track: 1 is the first belt.', unique=True)),
                ('colour', models.CharField(blank=True, default='', help_text='Hex colour for the belt swatch, e.g. "#f5c518".', max_length=7)),
                ('requirements', models.TextField(blank=True, default='', help_text='What a ninja must be able to do to get this belt.')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='belts/')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('one_off', 'One-off'), ('milestone', 'Milestone')], default='one_off', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('criteria', models.CharField(blank=True, default='', help_text='One-off: what earns it, e.g. "Attend a CoderDojo for Girls session."', max_length=200)),
                ('threshold', models.PositiveIntegerField(blank=True, help_text='Milestone: how many sessions a ninja must attend to reach it.', null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='awards/')),
                ('grants_belt', models.ForeignKey(blank=True, help_text='Milestone (optional): reaching it also grants this belt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_by_badges', to='events.belt')),
            ],
            options={
                'ordering': ['kind', 'threshold', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', help_text="Draft: hidden from the public site while it's being put together. Open: visible, registrations open. Closed: visible, registrations closed — set manually, normally once attendance for the session has been checked.", max_length=10)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('places', models.IntegerField()),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326)),
                ('venue_name', models.CharField(blank=True, default='', help_text='e.g. "Ghent Public Library"', max_length=200)),
                ('image', models.ImageField(blank=True, help_text="Banner shown on the homepage's Upcoming sessions card.", null=True, upload_to='events/')),
                ('description', models.TextField(blank=True, default='', help_text='Supports basic Markdown — # headings, **bold**, *italic*, links, lists.')),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dojos.dojo')),
                ('pathways', models.ManyToManyField(blank=True, help_text="The pathways this session covers (optional; shown on its public page). Pre-filled from the dojo's; registrations pre-select these.", related_name='events', to='pathways.pathway')),
                ('team', models.ManyToManyField(blank=True, help_text="Who ran (or will run) this session: members of the dojo's team.", related_name='events', to='dojos.dojomembership')),
            ],
        ),
        migrations.CreateModel(
            name='NinjaBelt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_on', models.DateField()),
                ('awarded_as_role', models.CharField(blank=True, default='', help_text="The membership's role when awarding.", max_length=20)),
                ('note', models.CharField(blank=True, default='', help_text='Optional: what the ninja showed.', max_length=300)),
                ('awarded_as_membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belts_awarded', to='dojos.dojomembership')),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belts_awarded', to=settings.AUTH_USER_MODEL)),
                ('belt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ninja_belts', to='events.belt')),
                ('ninja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belts', to='accounts.ninja')),
            ],
            options={
                'ordering': ['-awarded_on', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waiting_list', models.BooleanField()),
                ('position', models.IntegerField()),
                ('attended', models.BooleanField(blank=True, null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('ninja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ninja')),
                ('pathways', models.ManyToManyField(blank=True, help_text="What this ninja works on at this session — usually a subset of the event's pathways, which it's pre-filled from.", related_name='registrations', to='pathways.pathway')),
            ],
            options={
                'ordering': ['position'],
                'unique_together': {('event', 'ninja')},
            },
        ),
        migrations.AddField(
            model_name='event',
            name='ninjas',
            field=models.ManyToManyField(through='events.Registration', to='accounts.ninja'),
        ),
        migrations.CreateModel(
            name='NinjaBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateField(blank=True, help_text='Blank if still in progress.', null=True)),
                ('progress_current', models.PositiveIntegerField(blank=True, help_text='Milestone only.', null=True)),
                ('progress_total', models.PositiveIntegerField(blank=True, help_text='Milestone only.', null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninja_badges', to='events.badge')),
                ('ninja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.ninja')),
            ],
            options={
                'unique_together': {('ninja', 'badge')},
            },
        ),
    ]
