# Generated by Django 6.1.1 on 2026-09-22 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Supports basic Markdown — **bold**, *italic*, links, lists.'),
        ),
    ]
