# Generated by Django 6.0.8 on 2026-09-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='audience',
            field=models.CharField(choices=[('everyone', 'Everyone'), ('girls', "Girls' session")], default='everyone', help_text='Who the session is aimed at, shown as a label. It never restricts who can sign up.', max_length=10),
        ),
    ]
