# Generated by Django 6.1.1 on 2026-09-22 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Supports basic Markdown — # headings, **bold**, *italic*, links, lists.'),
        ),
        migrations.AlterField(
            model_name='event',
            name='what_to_bring',
            field=models.TextField(blank=True, default='', help_text='Supports basic Markdown — # headings, **bold**, *italic*, links, lists.'),
        ),
    ]
