# Generated by Django 6.0.8 on 2026-09-25 09:19

from django.db import migrations, models
from django.utils import timezone


def mark_existing_sessions_announced(apps, schema_editor):
    # Sessions that exist before the "new sessions" mail count as already
    # published and announced: the first digest after this deploy mustn't
    # mail every family about every open session at once.
    now = timezone.now()
    apps.get_model("events", "Event").objects.exclude(status="draft").update(published_at=now, announced_at=now)


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='announced_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='published_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.RunPython(mark_existing_sessions_announced, migrations.RunPython.noop),
    ]
