# Generated by Django 6.1.1 on 2026-09-22 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_description_alter_event_what_to_bring'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='what_to_bring',
        ),
    ]
