# Generated by Django 6.1.1 on 2026-09-25 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_language_postal_code'),
        ('dojos', '0001_initial'),
        ('events', '0003_event_published_announced'),
    ]

    operations = [
        migrations.CreateModel(
            name='NinjaEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('new', 'New'), ('regular', 'Regular'), ('occasional', 'Occasional'), ('at_risk', 'At risk'), ('lapsed', 'Lapsed'), ('never_attended', 'Never came'), ('aged_out', 'Aged out')], max_length=20)),
                ('first_attended', models.DateField(blank=True, null=True)),
                ('last_attended', models.DateField(blank=True, null=True)),
                ('attended_total', models.PositiveIntegerField(default=0)),
                ('attended_180d', models.PositiveIntegerField(default=0)),
                ('offered_180d', models.PositiveIntegerField(default=0, help_text='Sessions meant for the ninja, held in the window.')),
                ('attendance_rate', models.FloatField(default=0)),
                ('missed_in_a_row', models.PositiveIntegerField(default=0)),
                ('no_shows_90d', models.PositiveIntegerField(default=0)),
                ('has_upcoming', models.BooleanField(default=False)),
                ('from_marked_attendance', models.BooleanField(default=True, help_text='False when some counted visits are confirmed places at sessions nobody marked.')),
                ('computed_on', models.DateField()),
                ('dojo', models.ForeignKey(blank=True, help_text='Empty: the ninja overall, measured at their main dojo.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dojos.dojo')),
                ('main_dojo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dojos.dojo')),
                ('ninja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement', to='accounts.ninja')),
            ],
            options={
                'indexes': [models.Index(fields=['dojo', 'stage'], name='events_engagement_stage_idx')],
            },
        ),
    ]
