# Generated by Django 6.1.1 on 2026-09-25 12:58

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_language_postal_code'),
        ('events', '0004_ninja_engagement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, help_text='When the ninja was signed up.'),
        ),
        migrations.CreateModel(
            name='RegistrationCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('was_waitlisted', models.BooleanField()),
                ('signed_up_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='events.event')),
                ('ninja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='accounts.ninja')),
            ],
        ),
    ]
