# Generated by Django 6.1.1 on 2026-09-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_event_what_to_bring'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, help_text="Banner shown on the homepage's Upcoming sessions card.", null=True, upload_to='events/'),
        ),
    ]
