# Generated by Django 6.1.1 on 2026-09-25 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_language_postal_code'),
        ('events', '0005_registration_created_cancellations'),
    ]

    operations = [
        migrations.CreateModel(
            name='NinjaEngagementChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_stage', models.CharField(choices=[('new', 'New'), ('regular', 'Regular'), ('occasional', 'Occasional'), ('at_risk', 'At risk'), ('lapsed', 'Lapsed'), ('never_attended', 'Never came'), ('aged_out', 'Aged out')], max_length=20)),
                ('to_stage', models.CharField(choices=[('new', 'New'), ('regular', 'Regular'), ('occasional', 'Occasional'), ('at_risk', 'At risk'), ('lapsed', 'Lapsed'), ('never_attended', 'Never came'), ('aged_out', 'Aged out')], max_length=20)),
                ('changed_on', models.DateField()),
                ('ninja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='engagement_changes', to='accounts.ninja')),
            ],
            options={
                'indexes': [models.Index(fields=['changed_on', 'to_stage'], name='events_engagement_change_idx')],
            },
        ),
    ]
