# Generated by Django 6.1.1 on 2026-09-22 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_must_change_password'),
        ('events', '0005_event_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='registration',
            options={'ordering': ['position']},
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('event', 'participant')},
        ),
    ]
