# Generated by Django 6.1.1 on 2026-09-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_engagement_changes'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='external_registration_url',
            field=models.URLField(blank=True, default='', help_text='Registrations happen on another website (e.g. Coolest Projects): the event page links there instead of showing the sign-up form, so the event has no registrations or attendance on this site.'),
        ),
    ]
