# Generated by Django 6.1.1 on 2026-09-23 06:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_registration_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='criteria',
        ),
        migrations.CreateModel(
            name='MilestoneAward',
            fields=[
                ('award_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.award')),
                ('threshold', models.PositiveIntegerField(help_text='How many times something must happen to unlock this — e.g. 5 for "attend 5 sessions".')),
            ],
            bases=('events.award',),
        ),
        migrations.RemoveField(
            model_name='award',
            name='category',
        ),
        migrations.AddField(
            model_name='award',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='awards/'),
        ),
        migrations.CreateModel(
            name='BadgeAward',
            fields=[
                ('award_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='events.award')),
                ('criteria', models.CharField(blank=True, default='', help_text='e.g. "Attended a CoderDojo for Girls session."', max_length=200)),
            ],
            bases=('events.award',),
        ),
    ]
