# Generated by Django 6.1.1 on 2026-09-23 17:24

from django.db import migrations, models


def backfill_existing_events_as_open(apps, schema_editor):
    """Every Event that already exists at this point predates the status
    field entirely — it was implicitly public and open for registration
    (there was no other state). Only rows created *after* this migration
    runs pick up the model's real default (draft) — see events.views/
    dojos.views.dojo_event_create."""
    Event = apps.get_model("events", "Event")
    Event.objects.update(status="open")


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_award_criteria_milestoneaward_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed')], default='draft', help_text="Draft: hidden from the public site while it's being put together. Open: visible, registrations open. Closed: visible, registrations closed — set manually, normally once attendance for the session has been checked.", max_length=10),
        ),
        migrations.RunPython(backfill_existing_events_as_open, migrations.RunPython.noop),
    ]
