# Generated by Django 6.1.1 on 2026-09-23 17:59

from django.db import migrations, models


def copy_mentor_fk_into_mentors_m2m(apps, schema_editor):
    """An event could have at most one mentor before this migration — carry
    that single assignment over as the M2M's first (only) row, rather than
    silently dropping it once the old `mentor` column goes away below."""
    Event = apps.get_model("events", "Event")
    for event in Event.objects.exclude(mentor=None):
        event.mentors.add(event.mentor)


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0007_alter_mentor_owner_account_alter_mentor_role'),
        ('events', '0008_event_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='mentors',
            field=models.ManyToManyField(blank=True, related_name='events', to='dojos.mentor'),
        ),
        migrations.RunPython(copy_mentor_fk_into_mentors_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='event',
            name='mentor',
        ),
    ]
