# Generated by Django 6.1.1 on 2026-09-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0011_redesign_dojo_team'),
        ('events', '0009_remove_event_mentor_event_mentors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='mentors',
        ),
        migrations.AddField(
            model_name='event',
            name='team',
            field=models.ManyToManyField(blank=True, help_text="Who ran (or will run) this session: members of the dojo's team.", related_name='events', to='dojos.dojomembership'),
        ),
    ]
