# Generated by Django 6.1.1 on 2026-09-26 05:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0004_dojo_languages_by_region'),
        ('events', '0010_organisation_content_languages'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ninjabadge',
            name='awarded_as_membership',
            field=models.ForeignKey(blank=True, help_text='One-off only: the dojo team membership they awarded it as.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_awarded', to='dojos.dojomembership'),
        ),
        migrations.AddField(
            model_name='ninjabadge',
            name='awarded_by',
            field=models.ForeignKey(blank=True, help_text='One-off only: who awarded it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='badges_awarded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ninjabadge',
            name='note',
            field=models.CharField(blank=True, default='', help_text='Optional: what the ninja did.', max_length=300),
        ),
    ]
