# Generated by Django 6.1.1 on 2026-09-24 06:29

from django.db import migrations, models


def carry_over_pathways(apps, schema_editor):
    """Throwaway (dropped when migrations are reset in redesign phase 8):
    keeps an existing dev database's pathway data — each registration's
    single pathway becomes its pathway set, and events/dojos get the union
    of their registrations' pathways."""
    Registration = apps.get_model("events", "Registration")
    Event = apps.get_model("events", "Event")
    Dojo = apps.get_model("dojos", "Dojo")
    rows = list(Registration.objects.exclude(pathway=None).values_list("id", "pathway_id", "event_id", "event__dojo_id"))
    # Through-table inserts with ignore_conflicts: several registrations
    # share an event/dojo and pathway, and historical M2M .add() doesn't
    # skip existing pairs.
    Registration.pathways.through.objects.bulk_create(
        [Registration.pathways.through(registration_id=r, pathway_id=p) for r, p, _, _ in rows], ignore_conflicts=True,
    )
    Event.pathways.through.objects.bulk_create(
        [Event.pathways.through(event_id=e, pathway_id=p) for _, p, e, _ in rows], ignore_conflicts=True,
    )
    Dojo.pathways.through.objects.bulk_create(
        [Dojo.pathways.through(dojo_id=d, pathway_id=p) for _, p, _, d in rows], ignore_conflicts=True,
    )


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0013_redesign_pathways'),
        ('events', '0010_redesign_dojo_team'),
        ('pathways', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='pathways',
            field=models.ManyToManyField(blank=True, help_text="The pathways this session covers (optional; shown on its public page). Pre-filled from the dojo's; registrations pre-select these.", related_name='events', to='pathways.pathway'),
        ),
        migrations.AddField(
            model_name='registration',
            name='pathways',
            field=models.ManyToManyField(blank=True, help_text="What this ninja works on at this session — usually a subset of the event's pathways, which it's pre-filled from.", related_name='registrations', to='pathways.pathway'),
        ),
        migrations.RunPython(carry_over_pathways, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='registration',
            name='pathway',
        ),
    ]
