# Generated by Django 6.1.1 on 2026-09-24 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def carry_over_awards(apps, schema_editor):
    """Throwaway (dropped when migrations are reset in redesign phase 8):
    keeps an existing dev database's awards — each MilestoneAward/BadgeAward
    becomes a Badge of that kind, each ParticipantAward a NinjaBadge."""
    MilestoneAward = apps.get_model("events", "MilestoneAward")
    BadgeAward = apps.get_model("events", "BadgeAward")
    ParticipantAward = apps.get_model("events", "ParticipantAward")
    Badge = apps.get_model("events", "Badge")
    NinjaBadge = apps.get_model("events", "NinjaBadge")
    badge_for = {}
    for award in MilestoneAward.objects.all():
        badge_for[award.pk] = Badge.objects.create(
            name=award.name, kind="milestone", description=award.description,
            threshold=award.threshold, icon=award.icon.name or None,
        )
    for award in BadgeAward.objects.all():
        badge_for[award.pk] = Badge.objects.create(
            name=award.name, kind="one_off", description=award.description,
            criteria=award.criteria, icon=award.icon.name or None,
        )
    NinjaBadge.objects.bulk_create([
        NinjaBadge(
            participant_id=pa.participant_id, badge=badge_for[pa.award_id], earned_date=pa.earned_date,
            progress_current=pa.progress_current, progress_total=pa.progress_total,
        )
        for pa in ParticipantAward.objects.all() if pa.award_id in badge_for
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_redesign_onboarding'),
        ('dojos', '0013_redesign_pathways'),
        ('events', '0011_redesign_pathways'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Belt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. "Yellow belt".', max_length=100)),
                ('level', models.PositiveSmallIntegerField(help_text='Order on the track: 1 is the first belt.', unique=True)),
                ('colour', models.CharField(blank=True, default='', help_text='Hex colour for the belt swatch, e.g. "#f5c518".', max_length=7)),
                ('requirements', models.TextField(blank=True, default='', help_text='What a ninja must be able to do to get this belt.')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='belts/')),
            ],
            options={
                'ordering': ['level'],
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('one_off', 'One-off'), ('milestone', 'Milestone')], default='one_off', max_length=10)),
                ('description', models.CharField(blank=True, default='', max_length=300)),
                ('criteria', models.CharField(blank=True, default='', help_text='One-off: what earns it, e.g. "Attend a CoderDojo for Girls session."', max_length=200)),
                ('threshold', models.PositiveIntegerField(blank=True, help_text='Milestone: how many sessions a ninja must attend to reach it.', null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='awards/')),
                ('grants_belt', models.ForeignKey(blank=True, help_text='Milestone (optional): reaching it also grants this belt.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_by_badges', to='events.belt')),
            ],
            options={
                'ordering': ['kind', 'threshold', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NinjaBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_date', models.DateField(blank=True, help_text='Blank if still in progress.', null=True)),
                ('progress_current', models.PositiveIntegerField(blank=True, help_text='Milestone only.', null=True)),
                ('progress_total', models.PositiveIntegerField(blank=True, help_text='Milestone only.', null=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ninja_badges', to='events.badge')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='accounts.participant')),
            ],
            options={
                'unique_together': {('participant', 'badge')},
            },
        ),
        migrations.CreateModel(
            name='NinjaBelt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awarded_on', models.DateField()),
                ('awarded_as_role', models.CharField(blank=True, default='', help_text="The membership's role when awarding.", max_length=20)),
                ('note', models.CharField(blank=True, default='', help_text='Optional: what the ninja showed.', max_length=300)),
                ('awarded_as_membership', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belts_awarded', to='dojos.dojomembership')),
                ('awarded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='belts_awarded', to=settings.AUTH_USER_MODEL)),
                ('belt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ninja_belts', to='events.belt')),
                ('participant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='belts', to='accounts.participant')),
            ],
            options={
                'ordering': ['-awarded_on', '-id'],
            },
        ),
        migrations.RunPython(carry_over_awards, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='participantaward',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='participantaward',
            name='award',
        ),
        migrations.RemoveField(
            model_name='badgeaward',
            name='award_ptr',
        ),
        migrations.RemoveField(
            model_name='participantaward',
            name='participant',
        ),
        migrations.DeleteModel(
            name='MilestoneAward',
        ),
        migrations.DeleteModel(
            name='Award',
        ),
        migrations.DeleteModel(
            name='BadgeAward',
        ),
        migrations.DeleteModel(
            name='ParticipantAward',
        ),
    ]
