# Generated by Django 6.1.1 on 2026-09-30 22:36

import core.uploads
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_ninja_badge_awarded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='badge',
            name='icon',
            field=core.uploads.UploadedImageField(blank=True, max_side=512, null=True, upload_to='awards/'),
        ),
        migrations.AlterField(
            model_name='belt',
            name='icon',
            field=core.uploads.UploadedImageField(blank=True, max_side=512, null=True, upload_to='belts/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image',
            field=core.uploads.UploadedImageField(blank=True, help_text="Banner shown on the homepage's Upcoming sessions card.", max_side=1600, null=True, upload_to='events/'),
        ),
    ]
