# Generated by Django 6.0.8 on 2026-09-25 07:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_campaign_emailmessage_campaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='campaign',
            name='segment_snapshot',
            field=models.JSONField(default='null'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='campaign',
            name='segment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mailing.segment'),
        ),
        migrations.CreateModel(
            name='SegmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('and', 'And'), ('or', 'Or')], default='and', max_length=3)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='mailing.segment')),
            ],
        ),
        migrations.CreateModel(
            name='SegmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=50)),
                ('value', models.JSONField()),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='mailing.segment')),
            ],
        ),
    ]
