# Generated by Django 6.0.8 on 2026-09-25 08:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0005_remove_scaffolding_periodic_tasks'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('service', 'Account and security'), ('registration', 'Session bookings'), ('reminder', 'Reminders'), ('dojo_news', 'News from your dojo'), ('volunteer', 'Volunteering'), ('newsletter', 'Newsletter and campaigns')], max_length=20)),
                ('subscribed', models.BooleanField()),
                ('source', models.CharField(choices=[('signup', 'Sign-up form'), ('preferences', 'Mail preferences page'), ('unsubscribe_link', 'Unsubscribe link'), ('admin', 'Admin'), ('bounce', 'Bounce or complaint')], max_length=20)),
                ('wording_version', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailSuppression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Stored lower-case.', max_length=254, unique=True)),
                ('reason', models.CharField(choices=[('hard_bounce', 'Hard bounce'), ('complaint', 'Spam complaint'), ('manual', 'Blocked by hand')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('service', 'Account and security'), ('registration', 'Session bookings'), ('reminder', 'Reminders'), ('dojo_news', 'News from your dojo'), ('volunteer', 'Volunteering'), ('newsletter', 'Newsletter and campaigns')], max_length=20)),
                ('subscribed', models.BooleanField()),
                ('changed_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='provider_id',
        ),
        migrations.RemoveField(
            model_name='emailmessage',
            name='type',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='body',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='category',
            field=models.CharField(choices=[('service', 'Account and security'), ('registration', 'Session bookings'), ('reminder', 'Reminders'), ('dojo_news', 'News from your dojo'), ('volunteer', 'Volunteering'), ('newsletter', 'Newsletter and campaigns')], default='service', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='claimed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='language',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='message_id',
            field=models.CharField(blank=True, db_index=True, help_text='Our Message-ID header.', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='priority',
            field=models.PositiveSmallIntegerField(default=5, help_text='Lower is sent first.'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='send_after',
            field=models.DateTimeField(blank=True, help_text='Not sent before this time.', null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='status_reason',
            field=models.CharField(blank=True, help_text='Why it was suppressed or failed.', max_length=255),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='template_key',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='recipient',
            field=models.EmailField(blank=True, help_text='The address used, as it was at the time.', max_length=254),
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('bounced', 'Bounced'), ('suppressed', 'Not sent (no consent, no address or blocked)')], default='pending', max_length=20),
        ),
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status', 'priority', 'created_at'], name='mailing_queue_idx'),
        ),
        migrations.AddField(
            model_name='consentevent',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consent_events', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='mailpreference',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mail_preferences', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='mailpreference',
            constraint=models.UniqueConstraint(fields=('user', 'category'), name='unique_mail_preference'),
        ),
    ]
