# Generated by Django 6.0.8 on 2026-09-25 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0006_mail_queue_preferences_suppression'),
    ]

    operations = [
        migrations.CreateModel(
            name='BounceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Stored lower-case.', max_length=254)),
                ('kind', models.CharField(choices=[('hard', 'Hard bounce (5.x.x)'), ('soft', 'Soft bounce (4.x.x)'), ('complaint', 'Spam complaint')], max_length=10)),
                ('status_code', models.CharField(blank=True, help_text='e.g. 5.1.1', max_length=20)),
                ('diagnostic', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bounces', to='mailing.emailmessage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
