# Generated by Django 6.0.8 on 2026-09-25 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0007_bounce_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailsuppression',
            name='reason',
            field=models.CharField(choices=[('hard_bounce', 'Hard bounce'), ('soft_bounces', 'Repeated soft bounces'), ('complaint', 'Spam complaint'), ('manual', 'Blocked by hand')], max_length=20),
        ),
    ]
