# Generated by Django 6.1.1 on 2026-09-25 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0008_suppression_soft_bounces'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='launched_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='launched_by',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='queued_at',
            field=models.DateTimeField(blank=True, editable=False, help_text="When every recipient's mail was queued.", null=True),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='is_test',
            field=models.BooleanField(default=False, help_text="A campaign test sent to its author: preferences don't apply (blocks still do)."),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='scheduled_at',
            field=models.DateTimeField(blank=True, help_text="Leave empty to send as soon as it's launched.", null=True),
        ),
    ]
