# Generated by Django 6.1.1 on 2026-09-25 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0009_campaign_launch_test_mail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('service', 'Account and security'), ('registration', 'Session bookings'), ('reminder', 'Reminders'), ('dojo_news', 'News from your dojo'), ('volunteer', 'Volunteering'), ('newsletter', 'Newsletter and campaigns')], default='dojo_news', max_length=20)),
                ('template_key', models.CharField(max_length=100)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('cooldown_days', models.PositiveIntegerField(default=365, help_text="Someone who got it doesn't get it again for this many days.")),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='mailing.segment')),
            ],
        ),
        migrations.CreateModel(
            name='JourneyDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mailing.emailmessage')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='mailing.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['journey', 'user', 'created_at'], name='mailing_journey_delivery_idx')],
            },
        ),
    ]
