# Generated by Django 6.1.1 on 2026-09-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0010_journeys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('nl-be', 'Nederlands (België)'), ('fr-be', 'Français (Belgique)')], max_length=10),
        ),
    ]
