# Generated by Django 6.1.1 on 2026-09-29 15:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0004_dojo_languages_by_region'),
        ('mailing', '0012_login_link_template_updates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consentevent',
            name='dojo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dojos.dojo'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='dojo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dojos.dojo'),
        ),
        migrations.CreateModel(
            name='DojoMailMute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dojos.dojo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dojo_mail_mutes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'dojo'), name='unique_dojo_mail_mute')],
            },
        ),
    ]
