# Generated by Django 6.1.1 on 2026-09-29 15:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0004_dojo_languages_by_region'),
        ('mailing', '0013_dojo_mail_mute'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='audience',
            field=models.CharField(blank=True, help_text="A dojo mailing's audience (mailing.dojo_audiences).", max_length=30),
        ),
        migrations.AddField(
            model_name='campaign',
            name='audience_params',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='campaign',
            name='dojo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='dojos.dojo'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='message',
            field=models.TextField(blank=True, help_text="A dojo mailing's text (plain text), main language."),
        ),
        migrations.AddField(
            model_name='campaign',
            name='subject',
            field=models.CharField(blank=True, help_text="A dojo mailing's subject, main language.", max_length=150),
        ),
        migrations.AddField(
            model_name='campaign',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='The texts in the dojo\'s other languages: {"fr-be": {"field": "text"}}. The normal fields hold the main language. Edited on the dojo\'s dashboard pages.'),
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
