# Generated by Django 6.1.1 on 2026-10-02 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0014_dojo_mailings'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='queued_up_to',
            field=models.PositiveBigIntegerField(default=0, editable=False, help_text='The last account id whose mail is queued (the mail is queued in chunks, in id order).'),
        ),
    ]
