# Generated by Django 6.1.1 on 2026-10-02 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """Campaigns, segments and journeys moved to the campaigns app
    (campaigns 0001): state only, their tables stay as they are."""

    dependencies = [
        ('campaigns', '0001_initial'),
        ('mailing', '0015_campaign_queued_up_to'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.RemoveField(
            model_name='campaign',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='dojo',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='launched_by',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='segment',
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.campaign'),
        ),
        migrations.RemoveField(
            model_name='journey',
            name='segment',
        ),
        migrations.RemoveIndex(
            model_name='journeydelivery',
            name='mailing_journey_delivery_idx',
        ),
        migrations.RemoveField(
            model_name='segmentgroup',
            name='segment',
        ),
        migrations.RemoveField(
            model_name='segmentgroup',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='segmentrule',
            name='group',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.RemoveField(
            model_name='journeydelivery',
            name='email',
        ),
        migrations.RemoveField(
            model_name='journeydelivery',
            name='journey',
        ),
        migrations.RemoveField(
            model_name='journeydelivery',
            name='user',
        ),
        migrations.DeleteModel(
            name='Segment',
        ),
        migrations.DeleteModel(
            name='SegmentGroup',
        ),
        migrations.DeleteModel(
            name='SegmentRule',
        ),
        migrations.DeleteModel(
            name='Journey',
        ),
        migrations.DeleteModel(
            name='JourneyDelivery',
        ),
            ],
            database_operations=[],
        ),
    ]
