# Generated by Django 6.1.1 on 2026-10-03 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_audience_help_text'),
        ('dojos', '0005_alter_dojo_icon'),
        ('mailing', '0016_campaigns_moved_to_their_own_app'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='emailmessage',
            index=models.Index(fields=['status', 'sent_at'], name='mailing_sent_idx'),
        ),
    ]
