# Generated by Django 6.1.1 on 2026-10-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0017_sent_at_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='language',
            field=models.CharField(choices=[('en-us', 'English'), ('nl-be', 'Nederlands'), ('fr-be', 'Français')], max_length=10),
        ),
    ]
