# Generated by Django 6.1.1 on 2026-10-08 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0018_language_names_without_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(help_text='Stored lower-case, without the @.', max_length=253, unique=True)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
