# Generated by Django 6.1.1 on 2026-09-24 10:01

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackgroundCheckHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('validated', 'Validated'), ('rejected', 'Rejected')], max_length=10)),
                ('reviewed_at', models.DateTimeField()),
                ('requested_at', models.DateTimeField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='Validated checks only.', null=True)),
                ('note', models.TextField(blank=True, default='', help_text='Optional reviewer remark — never the document.')),
            ],
            options={
                'verbose_name_plural': 'background check history',
                'ordering': ['-reviewed_at'],
            },
        ),
        migrations.CreateModel(
            name='BackgroundCheck',
            fields=[
            ],
            options={
                'verbose_name': 'background check',
                'verbose_name_plural': 'background checks',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('accounts.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('mentor', 'Mentor'), ('champion', 'Champion (start a dojo)')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('mentor_role', models.CharField(blank=True, choices=[('volunteer_mentor', 'Volunteer mentor'), ('other', 'Something else (board, events, comms)')], default='', max_length=20)),
                ('area', models.CharField(blank=True, default='', help_text='City/area where the dojo would run.', max_length=200)),
                ('preferred_schedule', models.CharField(blank=True, default='', help_text='e.g. "Saturday mornings"', max_length=200)),
                ('proposed_venue', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='', help_text='Skills, interests, experience, anything useful.')),
                ('consent', models.BooleanField(default=False, help_text='Champions: understands sessions are free and volunteer-run.')),
                ('background_check_consent', models.BooleanField(default=False, help_text='Understands a Belgian criminal record extract (model 2, Artikel 596.2) is required before working with minors.')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-submitted_at'],
                'permissions': [('can_review_background_checks', 'Can review background check documents')],
            },
        ),
    ]
