# Generated by Django 6.1.1 on 2026-09-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dojos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DojoApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(blank=True, default='', max_length=30)),
                ('area', models.CharField(help_text='City/area where the dojo would run.', max_length=200)),
                ('preferred_schedule', models.CharField(blank=True, default='', help_text='e.g. "Saturday mornings"', max_length=200)),
                ('proposed_venue', models.CharField(blank=True, default='', max_length=200)),
                ('message', models.TextField(blank=True, default='')),
                ('consent', models.BooleanField(default=False, help_text='Understands sessions are free and volunteer-run.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MentorApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicant_name', models.CharField(max_length=200)),
                ('applicant_email', models.EmailField(max_length=254)),
                ('applicant_phone', models.CharField(blank=True, default='', max_length=30)),
                ('role', models.CharField(choices=[('volunteer_mentor', 'Volunteer mentor'), ('other', 'Something else (board, events, comms)')], default='volunteer_mentor', max_length=20)),
                ('about', models.TextField(blank=True, default='', help_text="Applicant's skills/interests.")),
                ('background_check_consent', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('dojo', models.ForeignKey(blank=True, help_text='Blank if the applicant is open to any dojo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_applications', to='dojos.dojo')),
            ],
        ),
    ]
