# Generated by Django 6.1.1 on 2026-09-24 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('dojos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='dojo',
            field=models.ForeignKey(blank=True, help_text="Mentor applications: the dojo they'd like to help at (blank = any). Approval files a join request there.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='dojos.dojo'),
        ),
        migrations.AddField(
            model_name='backgroundcheckhistory',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='background_check_history', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='backgroundcheckhistory',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
