# Generated by Django 6.1.1 on 2026-09-23 07:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojoapplication',
            name='background_check_consent',
            field=models.BooleanField(default=False, help_text="Understands a Belgian criminal record extract (model 2, Artikel 596.2) will be required, since a dojo's lead coach works directly with minors."),
        ),
        migrations.AddField(
            model_name='dojoapplication',
            name='background_check_document',
            field=models.FileField(blank=True, help_text="The applicant's uittreksel uit het strafregister, model 2 (Artikel 596.2).", null=True, upload_to='background_checks/'),
        ),
        migrations.AddField(
            model_name='dojoapplication',
            name='background_check_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dojoapplication',
            name='background_check_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dojoapplication',
            name='background_check_status',
            field=models.CharField(choices=[('not_requested', 'Not requested yet'), ('requested', 'Requested — waiting on applicant'), ('submitted', 'Submitted — awaiting review'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='not_requested', max_length=20),
        ),
        migrations.AddField(
            model_name='dojoapplication',
            name='background_check_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dojoapplication',
            name='background_check_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='background_check_document',
            field=models.FileField(blank=True, help_text="The applicant's uittreksel uit het strafregister, model 2 (Artikel 596.2).", null=True, upload_to='background_checks/'),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='background_check_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='background_check_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='background_check_status',
            field=models.CharField(choices=[('not_requested', 'Not requested yet'), ('requested', 'Requested — waiting on applicant'), ('submitted', 'Submitted — awaiting review'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='not_requested', max_length=20),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='background_check_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='background_check_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='background_check_consent',
            field=models.BooleanField(default=False, help_text='Understands a Belgian criminal record extract (model 2, Artikel 596.2) will be required before working directly with minors.'),
        ),
    ]
