# Generated by Django 6.1.1 on 2026-09-23 07:08

import django.core.files.storage
import pathlib
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_dojoapplication_background_check_consent_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dojoapplication',
            options={'permissions': [('can_review_background_checks', 'Can review background check documents')]},
        ),
        migrations.AddField(
            model_name='dojoapplication',
            name='background_check_expires_at',
            field=models.DateTimeField(blank=True, help_text='Set on validation; the check must be redone after this date.', null=True),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='background_check_expires_at',
            field=models.DateTimeField(blank=True, help_text='Set on validation; the check must be redone after this date.', null=True),
        ),
        migrations.AlterField(
            model_name='dojoapplication',
            name='background_check_document',
            field=models.FileField(blank=True, help_text="The applicant's uittreksel uit het strafregister, model 2 (Artikel 596.2). Only readable by an approved reviewer (applications.can_review_background_checks) via the protected download view — never a public media URL. The file itself is deleted once validated; only the decision and its expiry date are kept.", null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PurePosixPath('/home/erik/coderdojo-event-registration/private_media')), upload_to='background_checks/'),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='background_check_document',
            field=models.FileField(blank=True, help_text="The applicant's uittreksel uit het strafregister, model 2 (Artikel 596.2). Only readable by an approved reviewer (applications.can_review_background_checks) via the protected download view — never a public media URL. The file itself is deleted once validated; only the decision and its expiry date are kept.", null=True, storage=django.core.files.storage.FileSystemStorage(base_url=None, location=pathlib.PurePosixPath('/home/erik/coderdojo-event-registration/private_media')), upload_to='background_checks/'),
        ),
    ]
