# Generated by Django 6.1.1 on 2026-09-23 14:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_background_check_expires_at_and_more'),
        ('applications', '0003_alter_dojoapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojoapplication',
            name='provisioned_owner',
            field=models.OneToOneField(blank=True, help_text='Set by approve_and_provision_owner. Lets a later background-check renewal (validate_background_check, re-run on this same row) sync the new expiry back onto the account that logs in with it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='accounts.dojoowner'),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='provisioned_helper',
            field=models.OneToOneField(blank=True, help_text='Set by approve_and_provision_helper. Lets a later background-check renewal (validate_background_check, re-run on this same row) sync the new expiry back onto the account that logs in with it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='accounts.helperaccount'),
        ),
    ]
