# Generated by Django 6.1.1 on 2026-09-25 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pathway',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='The texts in the dojo\'s other languages: {"fr-be": {"field": "text"}}. The normal fields hold the main language. Edited on the dojo\'s dashboard pages.'),
        ),
        migrations.AddField(
            model_name='pathwayproject',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='The texts in the dojo\'s other languages: {"fr-be": {"field": "text"}}. The normal fields hold the main language. Edited on the dojo\'s dashboard pages.'),
        ),
        migrations.AddField(
            model_name='pathwaystep',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='The texts in the dojo\'s other languages: {"fr-be": {"field": "text"}}. The normal fields hold the main language. Edited on the dojo\'s dashboard pages.'),
        ),
        migrations.AddField(
            model_name='skill',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='The texts in the dojo\'s other languages: {"fr-be": {"field": "text"}}. The normal fields hold the main language. Edited on the dojo\'s dashboard pages.'),
        ),
    ]
