# Generated by Django 6.1.1 on 2026-09-30 22:36

import core.uploads
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pathways', '0002_organisation_content_languages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pathway',
            name='image',
            field=core.uploads.UploadedImageField(blank=True, max_side=1600, null=True, upload_to='pathways/'),
        ),
    ]
