import json
import re
import time

import requests
from bs4 import BeautifulSoup
from django.contrib.gis.db.models.functions import Distance
from django.contrib.gis.geos import Point
from django.core.management.base import BaseCommand

from dojos.models import Dojo
from geo.geocoding import USER_AGENT, geocode
from geo.models import Municipality

DOJOS_URL = "https://coderdojobelgium.be/nl/dojos"
NOMINATIM_DELAY_SECONDS = 5  # Nominatim usage policy: max 1 request/second


def scrape_dojos(html):
    """Extract {name, address} for every dojo marker on the CoderDojo Belgium dojo finder page."""
    # The map widget's id (e.g. 'map-sinmgm') is regenerated by the CMS on
    # every page load, so match it as a wildcard rather than a fixed value.
    match = re.search(r"_gmData\.infoWindows\['map-\w+'\]\s*=\s*(\{.*?\});", html, re.S)
    if not match:
        return []

    blob = match.group(1)
    parts = re.split(r"\n\s*'(\d+-locationAddress)':\s*", blob)
    ids, raw_values = parts[1::2], parts[2::2]

    dojos = []
    for marker_id, raw_value in zip(ids, raw_values):
        obj_match = re.match(r'\{"content":"(?:[^"\\]|\\.)*"\}', raw_value)
        if not obj_match:
            continue
        content_html = json.loads(obj_match.group(0))["content"]
        soup = BeautifulSoup(content_html, "html.parser")

        name_el = soup.select_one("h3")
        address_el = soup.select_one(".address")
        if not name_el:
            continue

        dojos.append({
            "id": marker_id,
            "name": name_el.get_text(strip=True),
            "address": address_el.get_text(strip=True) if address_el else "",
        })
    return dojos


def find_nearest_municipality(lat, lon):
    point = Point(lon, lat, srid=4326)
    return (
        Municipality.objects.annotate(distance=Distance("center", point))
        .order_by("distance")
        .first()
    )


class Command(BaseCommand):
    help = (
        "Import dojos (with geocoded location) from the CoderDojo Belgium dojo finder "
        "page. Hits the live site + Nominatim, so it's slow and network-dependent - for "
        "local dev/container seeding use `manage.py seed_dojos` instead, which loads a "
        "bundled dump of this command's output."
    )

    def add_arguments(self, parser):
        parser.add_argument(
            "--dry-run",
            action="store_true",
            help="Scrape and geocode but don't write anything to the database.",
        )

    def handle(self, *args, **options):
        dry_run = options["dry_run"]

        response = requests.get(DOJOS_URL, headers={"User-Agent": USER_AGENT}, timeout=30)
        response.raise_for_status()
        entries = scrape_dojos(response.text)
        self.stdout.write(f"Found {len(entries)} dojo markers on {DOJOS_URL}")

        session = requests.Session()
        created, updated, unchanged, skipped = 0, 0, 0, 0

        for entry in entries:
            name, address = entry["name"], entry["address"]

            existing = Dojo.objects.filter(name=name).first()
            if existing and existing.address == address:
                unchanged += 1
                continue

            municipality, location = None, None

            if address:
                time.sleep(NOMINATIM_DELAY_SECONDS)
                try:
                    coords = geocode(address, session=session)
                except requests.RequestException as exc:
                    self.stderr.write(self.style.WARNING(f"Skipping '{name}': geocoding request failed ({exc})"))
                    skipped += 1
                    continue

                if coords is None:
                    self.stderr.write(self.style.WARNING(f"Skipping '{name}': Nominatim found no match for '{address}'"))
                    skipped += 1
                    continue

                lat, lon = coords
                municipality = find_nearest_municipality(lat, lon)
                if not municipality:
                    self.stderr.write(self.style.WARNING(f"Skipping '{name}': no municipalities in the database"))
                    skipped += 1
                    continue

                location = Point(lon, lat, srid=4326)
                self.stdout.write(
                    f"{'Would create' if dry_run else 'Saving'} '{name}' at {address} "
                    f"-> ({lat}, {lon}), municipality={municipality}"
                )
            else:
                self.stdout.write(f"{'Would create' if dry_run else 'Saving'} '{name}' (no address)")

            if dry_run:
                created += 1 if existing is None else 0
                updated += 1 if existing is not None else 0
                continue

            _, was_created = Dojo.objects.update_or_create(
                name=name,
                defaults={
                    "municipality": municipality,
                    "address": address,
                    "location": location,
                },
            )
            created += 1 if was_created else 0
            updated += 1 if not was_created else 0

        self.stdout.write(self.style.SUCCESS(
            f"Done. created={created} updated={updated} unchanged={unchanged} skipped={skipped}"
        ))
