# Generated by Django 6.1.1 on 2026-09-26 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ErasureRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('object_id', models.PositiveBigIntegerField()),
                ('keep_visible', models.BooleanField(default=False)),
                ('reason', models.CharField(choices=[('request', 'On request'), ('retention', 'Retention: two years without logging in')], max_length=20)),
                ('erased_at', models.DateTimeField(auto_now_add=True)),
                ('requested_by', models.ForeignKey(blank=True, help_text='The organisation admin who asked for it; empty for the retention job.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['model', 'object_id'], name='privacy_era_model_683efc_idx')],
            },
        ),
        migrations.CreateModel(
            name='RetentionNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inactive_since', models.DateTimeField()),
                ('days_before', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retention_notices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'inactive_since', 'days_before'), name='unique_retention_notice')],
            },
        ),
    ]
