# Generated by Django 6.1.1 on 2026-09-26 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('privacy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='erasurerecord',
            name='reason',
            field=models.CharField(choices=[('self', 'By the account holder'), ('request', 'On request, by the organisation'), ('retention', 'Retention: two years without logging in')], max_length=20),
        ),
    ]
