# Generated by Django 6.1.1 on 2026-09-26 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dojos', '0004_dojo_languages_by_region'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        migrations.swappable_dependency(settings.OAUTH2_PROVIDER_APPLICATION_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DojoApiClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='What the dojo calls it, e.g. "Scan app at the door".', max_length=100)),
                ('scopes', models.JSONField(default=list, help_text='What it may do: attendance:read, attendance:write.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(limit_choices_to={'account_type': 'service'}, on_delete=django.db.models.deletion.CASCADE, related_name='api_client', to=settings.AUTH_USER_MODEL)),
                ('application', models.OneToOneField(help_text='Its OAuth 2.0 client (ID and hashed secret).', on_delete=django.db.models.deletion.CASCADE, related_name='dojo_client', to=settings.OAUTH2_PROVIDER_APPLICATION_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_clients', to='dojos.dojo')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
