# Generated by Django 6.1.1 on 2026-09-24 10:01

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import applications.storage


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('board', 'Board (read-only)'), ('admin', 'Admin')], max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('must_change_password', models.BooleanField(default=False, help_text='Forces a password change on next login (e.g. set by an admin who reset it). Enforced by accounts.middleware.ForcePasswordChangeMiddleware.')),
                ('background_check_status', models.CharField(choices=[('not_requested', 'Not requested yet'), ('requested', 'Requested — waiting on the account holder'), ('submitted', 'Submitted — awaiting review'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='not_requested', max_length=20)),
                ('background_check_token', models.UUIDField(blank=True, editable=False, help_text='Set when a check is requested; builds the emailed upload link.', null=True, unique=True)),
                ('background_check_document', models.FileField(blank=True, help_text='The uploaded uittreksel uit het strafregister, model 2 (Artikel 596.2). Only readable by a reviewer (applications.can_review_background_checks) via the protected download view — never a public media URL. Deleted as soon as a decision is made; only the decision is kept.', null=True, storage=applications.storage.get_private_storage, upload_to='background_checks/')),
                ('background_check_requested_at', models.DateTimeField(blank=True, null=True)),
                ('background_check_submitted_at', models.DateTimeField(blank=True, null=True)),
                ('background_check_reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('background_check_expires_at', models.DateTimeField(blank=True, help_text='Set on validation; the check must be redone after this date.', null=True)),
                ('account_type', models.CharField(choices=[('adult', 'Adult'), ('ninja', 'Ninja')], default='adult', max_length=10)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('display_name', models.CharField(blank=True, default='', help_text='How this person is named on team pages; defaults to their full name.', max_length=150)),
                ('title', models.CharField(blank=True, default='', help_text='e.g. "Software engineer"', max_length=200)),
                ('bio', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('show_on_team_pages', models.BooleanField(default=True, help_text='Uncheck to keep this person off the public team pages.')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('parent', 'Parent'), ('legal_guardian', 'Legal guardian'), ('other', 'Other')], default='parent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(limit_choices_to={'account_type': 'adult'}, on_delete=django.db.models.deletion.CASCADE, related_name='guardianships', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ninja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('member_since', models.DateField(blank=True, null=True)),
                ('experience_level', models.CharField(blank=True, choices=[('new', 'New to coding'), ('some', 'Some experience'), ('confident', 'Confident')], default='', max_length=10)),
                ('allergies_notes', models.TextField(blank=True, default='', help_text='Allergies or other notes for mentors.')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='participants/')),
                ('account', models.OneToOneField(blank=True, help_text="The child's own login (an account of type ninja) — set only if a parent has allowed it.", limit_choices_to={'account_type': 'ninja'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ninja', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
