# Generated by Django 6.1.1 on 2026-09-22 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dojos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='home_dojo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_participants', to='dojos.dojo'),
        ),
        migrations.AddField(
            model_name='participant',
            name='account',
            field=models.OneToOneField(blank=True, help_text='Set only if the guardian has allowed this child to have their own login.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participant', to='accounts.childaccount'),
        ),
        migrations.AddField(
            model_name='participant',
            name='guardian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='accounts.guardian'),
        ),
    ]
