# Generated by Django 6.1.1 on 2026-09-24 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('dojos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='home_dojo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_ninjas', to='dojos.dojo'),
        ),
        migrations.AddField(
            model_name='guardianship',
            name='ninja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships', to='accounts.ninja'),
        ),
        migrations.AddField(
            model_name='organisationrole',
            name='account',
            field=models.ForeignKey(limit_choices_to={'account_type': 'adult'}, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_roles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='guardianship',
            constraint=models.UniqueConstraint(fields=('guardian', 'ninja'), name='unique_guardianship'),
        ),
        migrations.AddConstraint(
            model_name='organisationrole',
            constraint=models.UniqueConstraint(fields=('account', 'role'), name='unique_organisation_role'),
        ),
    ]
