# Generated by Django 6.1.1 on 2026-09-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ninja',
            name='experience_level',
        ),
    ]
