# Generated by Django 6.0.8 on 2026-09-25 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_ninja_experience_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='gender',
            field=models.CharField(choices=[('girl', 'Girl'), ('boy', 'Boy'), ('other', 'Other'), ('unspecified', 'Prefer not to say')], default='unspecified', help_text="Optional, never shown publicly. Used to let families know about girls' sessions (Event.audience), never to restrict who can sign up.", max_length=12),
        ),
    ]
