# Generated by Django 6.1.1 on 2026-09-22 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_helperaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Forces a password change on next login — set when an admin provisions an account (DojoOwner, HelperAccount) with a temporary password. Enforced by accounts.middleware.ForcePasswordChangeMiddleware.'),
        ),
    ]
