# Generated by Django 6.1.1 on 2026-09-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_must_change_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='background_check_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='background_check_required',
            field=models.BooleanField(default=False, help_text="Set at provisioning time from the linked application's background_check_required (age-based — see BACKGROUND_CHECK_MINIMUM_AGE). When true, login is refused once background_check_expires_at lapses — see accounts.backends and accounts.middleware.BackgroundCheckMiddleware — until a reviewer validates a fresh one (applications.admin.validate_background_check syncs the new expiry back here)."),
        ),
    ]
