# Generated by Django 6.0.8 on 2026-09-25 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_ninja_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='postal_code',
            field=models.CharField(blank=True, default='', help_text='Belgian postcode where the family lives (geo.Municipality.postal_code). Used to tell families about dojos and sessions near them, never shown publicly.', max_length=4),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('nl-be', 'Nederlands (België)'), ('fr-be', 'Français (Belgique)'), ('de', 'Deutsch')], default='', help_text="The language mails are sent in. Set from the site's language at sign-up; empty means the default (English).", max_length=10),
        ),
    ]
