# Generated by Django 6.1.1 on 2026-09-25 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_language_postal_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('nl-be', 'Nederlands (België)'), ('fr-be', 'Français (Belgique)')], default='', help_text="The language mails are sent in. Set from the site's language at sign-up; empty means the default (English).", max_length=10),
        ),
    ]
