# Generated by Django 6.1.1 on 2026-09-24 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def carry_over_family_links(apps, schema_editor):
    """Throwaway (dropped when migrations are reset in redesign phase 8):
    keeps an existing dev database usable by turning each old
    Participant.guardian link into a Guardianship and marking former
    ChildAccount logins as ninja accounts."""
    Participant = apps.get_model("accounts", "Participant")
    Guardianship = apps.get_model("accounts", "Guardianship")
    User = apps.get_model("accounts", "User")
    ChildAccount = apps.get_model("accounts", "ChildAccount")
    Guardianship.objects.bulk_create(
        [Guardianship(guardian_id=p.guardian_id, ninja_id=p.id)
         for p in Participant.objects.exclude(guardian_id=None)],
        ignore_conflicts=True,
    )
    User.objects.filter(id__in=ChildAccount.objects.values("user_ptr_id")).update(account_type="ninja")


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_background_check_expires_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('adult', 'Adult'), ('ninja', 'Ninja')], default='adult', max_length=10),
        ),
        migrations.AlterField(
            model_name='participant',
            name='account',
            field=models.OneToOneField(blank=True, help_text="The child's own login (an account of type ninja) — set only if a parent has allowed it.", limit_choices_to={'account_type': 'ninja'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ninja', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Guardianship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation', models.CharField(choices=[('parent', 'Parent'), ('legal_guardian', 'Legal guardian'), ('other', 'Other')], default='parent', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guardian', models.ForeignKey(limit_choices_to={'account_type': 'adult'}, on_delete=django.db.models.deletion.CASCADE, related_name='guardianships', to=settings.AUTH_USER_MODEL)),
                ('ninja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guardianships', to='accounts.participant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('guardian', 'ninja'), name='unique_guardianship')],
            },
        ),
        migrations.RunPython(carry_over_family_links, migrations.RunPython.noop),
    ]
