# Generated by Django 6.1.1 on 2026-09-24 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_redesign_guardianship'),
        # Mentor's guardian/child links must point at User before those tables go.
        ('dojos', '0010_redesign_guardianship'),
    ]

    operations = [
        # First: MySQL won't drop guardian's key column while this FK still points at it.
        migrations.RemoveField(
            model_name='participant',
            name='guardian',
        ),
        migrations.RemoveField(
            model_name='guardian',
            name='user_ptr',
        ),
        migrations.DeleteModel(
            name='ChildAccount',
        ),
        migrations.DeleteModel(
            name='Guardian',
        ),
        # Last: Guardian had its own `phone`, which would clash with this one while it exists.
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
