# Generated by Django 6.1.1 on 2026-09-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_drop_german'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninja',
            name='allergies_notes',
            field=models.TextField(blank=True, default='', help_text='Allergies or other notes from the family (health data). Shown to the champion only, on the attendance list of a session the child has a confirmed place at.'),
        ),
    ]
