# Generated by Django 6.1.1 on 2026-09-26 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_allergies_notes_help'),
    ]

    operations = [
        migrations.AddField(
            model_name='guardianship',
            name='consent_given_at',
            field=models.DateTimeField(blank=True, help_text="When the guardian agreed to the child's data being kept; empty for links made before the consent was asked, or made in the admin.", null=True),
        ),
        migrations.AddField(
            model_name='guardianship',
            name='consent_wording_version',
            field=models.CharField(blank=True, default='', help_text='The wording agreed to (accounts.consent).', max_length=20),
        ),
    ]
