# Generated by Django 6.1.1 on 2026-09-24 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_redesign_drop_guardian_childaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='display_name',
            field=models.CharField(blank=True, default='', help_text='How this person is named on team pages; defaults to their full name.', max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='user',
            name='show_on_team_pages',
            field=models.BooleanField(default=True, help_text='Uncheck to keep this person off the public team pages.'),
        ),
        migrations.AddField(
            model_name='user',
            name='title',
            field=models.CharField(blank=True, default='', help_text='e.g. "Software engineer"', max_length=200),
        ),
    ]
