# Generated by Django 6.1.1 on 2026-09-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_guardianship_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('adult', 'Adult'), ('ninja', 'Ninja'), ('service', 'API client (technical)')], default='adult', max_length=10),
        ),
    ]
