# Generated by Django 6.1.1 on 2026-09-24 06:19

import applications.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_redesign_dojo_team'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='background_check_required',
        ),
        migrations.AddField(
            model_name='user',
            name='background_check_document',
            field=models.FileField(blank=True, help_text='The uploaded uittreksel uit het strafregister, model 2 (Artikel 596.2). Only readable by a reviewer (applications.can_review_background_checks) via the protected download view — never a public media URL. Deleted as soon as a decision is made; only the decision is kept.', null=True, storage=applications.storage.get_private_storage, upload_to='background_checks/'),
        ),
        migrations.AddField(
            model_name='user',
            name='background_check_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='background_check_reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='background_check_status',
            field=models.CharField(choices=[('not_requested', 'Not requested yet'), ('requested', 'Requested — waiting on the account holder'), ('submitted', 'Submitted — awaiting review'), ('validated', 'Validated'), ('rejected', 'Rejected')], default='not_requested', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='background_check_submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='background_check_token',
            field=models.UUIDField(blank=True, editable=False, help_text='Set when a check is requested; builds the emailed upload link.', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='background_check_expires_at',
            field=models.DateTimeField(blank=True, help_text='Set on validation; the check must be redone after this date.', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Forces a password change on next login (e.g. set by an admin who reset it). Enforced by accounts.middleware.ForcePasswordChangeMiddleware.'),
        ),
    ]
