# Generated by Django 6.1.1 on 2026-09-24 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_redesign_onboarding'),
        ('applications', '0007_redesign_onboarding'),
    ]

    operations = [
        # Straight DeleteModel, no RemoveField('user_ptr') first: these MTI tables hold only
        # that column, and MySQL refuses to drop a table's last column (error 1090).
        # Runs after applications 0007, which drops the old application FKs to these tables.
        migrations.DeleteModel(
            name='DojoOwner',
        ),
        migrations.DeleteModel(
            name='HelperAccount',
        ),
    ]
