# Generated by Django 6.1.1 on 2026-09-27 03:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_service_account_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignInRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('superuser', 'Superusers'), ('organisation_admin', 'Organisation admins'), ('organisation_board', 'Board members'), ('reviewer', 'Background-check reviewers'), ('champion', 'Champions'), ('mentor', 'Mentors'), ('adult', 'Every adult account (parents too)')], max_length=20, unique=True)),
                ('level', models.CharField(choices=[('password', 'Password only (two-step login optional)'), ('two_step', 'Two-step login (authenticator app or passkey)'), ('passkey', 'Two-step login with a passkey')], default='password', max_length=10)),
                ('required_from', models.DateField(blank=True, help_text='From this day on the level is required; before it, the accounts see a notice. Empty = right away.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['role'],
            },
        ),
    ]
