# Generated by Django 6.1.1 on 2026-09-27 04:44

from django.db import migrations, models


def split_family_names(apps, schema_editor):
    """Children were stored with one name, often "First Family". Split off the
    family name only where it's certain: the name ends with the family name
    of one of the child's guardians. Anything else stays as it was (the
    family can fill in the family name on the child's page)."""
    Ninja = apps.get_model("accounts", "Ninja")
    Guardianship = apps.get_model("accounts", "Guardianship")
    for ninja in Ninja.objects.filter(family_name=""):
        family_names = Guardianship.objects.filter(ninja=ninja).values_list("guardian__last_name", flat=True)
        for family_name in sorted({f.strip() for f in family_names if f.strip()}, key=len, reverse=True):
            first, _, rest = ninja.name.strip().rpartition(" " + family_name)
            if first and rest == "":
                ninja.name, ninja.family_name = first.strip(), family_name
                ninja.save(update_fields=["name", "family_name"])
                break


def join_family_names(apps, schema_editor):
    Ninja = apps.get_model("accounts", "Ninja")
    for ninja in Ninja.objects.exclude(family_name=""):
        ninja.name = f"{ninja.name} {ninja.family_name}"
        ninja.save(update_fields=["name"])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_sign_in_requirement'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='family_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ninja',
            name='name',
            field=models.CharField(max_length=200, verbose_name='first name'),
        ),
        migrations.RunPython(split_family_names, join_family_names),
    ]
