# Generated by Django 6.1.1 on 2026-09-24 09:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_redesign_onboarding'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('board', 'Board (read-only)'), ('admin', 'Admin')], max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(limit_choices_to={'account_type': 'adult'}, on_delete=django.db.models.deletion.CASCADE, related_name='organisation_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('account', 'role'), name='unique_organisation_role')],
            },
        ),
    ]
