# Generated by Django 6.1.1 on 2026-09-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_ninja_family_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationrole',
            name='role',
            field=models.CharField(choices=[('board', 'Board (read-only)'), ('admin', 'Admin'), ('reviewer', 'Background-check reviewer')], max_length=10),
        ),
    ]
