# Generated by Django 6.1.1 on 2026-09-29 08:02

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0015_staff_only_with_admin_access"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organisationrole",
            options={
                "permissions": [
                    (
                        "manage_communication",
                        "Organisation dashboard: campaigns, journeys, segments and mail templates",
                    ),
                    ("manage_public_site", "Organisation dashboard: promotions and sponsors"),
                    ("manage_ninjas", "Organisation dashboard: awards"),
                    ("manage_privacy", "Organisation dashboard: privacy (data export, deletion, email change)"),
                    ("manage_security", "Organisation dashboard: sign-in security"),
                    ("manage_people", "Organisation dashboard: people and their organisation roles"),
                ]
            },
        ),
    ]
