# Generated by Django 6.1.1 on 2026-09-29 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_organisation_invitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_method',
            field=models.CharField(choices=[('password', 'Password'), ('link', 'Login link by email')], default='password', help_text='Password, or a login link mailed each time (then the account has no usable password). Changed by the account holder on Sign-in security (accounts/login_links.py).', max_length=10),
        ),
    ]
