# Generated by Django 6.1.1 on 2026-09-29 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_login_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signinrequirement',
            name='level',
            field=models.CharField(choices=[('password', 'Password or login link (two-step login optional)'), ('two_step', 'Two-step login (authenticator app or passkey)'), ('passkey', 'Two-step login with a passkey')], default='password', max_length=10),
        ),
    ]
