# Generated by Django 6.1.1 on 2026-09-30 22:36

import applications.storage
import core.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_password_level_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ninja',
            name='photo',
            field=core.uploads.UploadedImageField(blank=True, max_side=512, null=True, upload_to='participants/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='background_check_document',
            field=models.FileField(blank=True, help_text='The uploaded uittreksel uit het strafregister, model 2 (Artikel 596.2). Only readable by a reviewer (applications.can_review_background_checks) via the protected download view — never a public media URL. Deleted as soon as a decision is made; only the decision is kept.', null=True, storage=applications.storage.get_private_storage, upload_to='background_checks/', validators=[core.uploads.validate_document_upload]),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=core.uploads.UploadedImageField(blank=True, max_side=512, null=True, upload_to='profiles/'),
        ),
    ]
