# Generated by Django 6.1.1 on 2026-10-03 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_ninja_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='preferred_language',
            field=models.CharField(blank=True, choices=[('en-us', 'English'), ('nl-be', 'Nederlands'), ('fr-be', 'Français')], default='', help_text="The language mails are sent in. Set from the site's language at sign-up; empty means the default (English).", max_length=10),
        ),
    ]
