# Generated by Django 6.1.1 on 2026-09-22 15:38

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326)),
                ('description', models.TextField(blank=True, default='')),
                ('schedule_description', models.CharField(blank=True, default='', help_text='e.g. "Every 2nd Saturday"', max_length=200)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('quote', models.TextField(blank=True, default='')),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.municipality')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dojos', to='accounts.dojoowner')),
                ('province', models.ForeignKey(blank=True, limit_choices_to={'kind': 'province'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dojos', to='geo.administrativeboundary')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('champion', 'Dojo champion'), ('ninja', 'Ninja mentor'), ('volunteer', 'Volunteer mentor'), ('board', 'Board member')], max_length=20)),
                ('title', models.CharField(blank=True, default='', help_text='e.g. "Software engineer"', max_length=200)),
                ('bio', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='mentors/')),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('sessions_run', models.PositiveIntegerField(blank=True, null=True)),
                ('focus_areas', models.CharField(blank=True, default='', help_text='Comma-separated, board members only, e.g. "Volunteer recruitment, Partnerships"', max_length=300)),
                ('dojo', models.ForeignKey(blank=True, help_text='Left blank for board members, who work across dojos.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentors', to='dojos.dojo')),
            ],
        ),
        migrations.AddField(
            model_name='dojo',
            name='quote_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quoted_on_dojos', to='dojos.mentor'),
        ),
    ]
