# Generated by Django 6.1.1 on 2026-09-24 10:01

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geo', '0001_initial'),
        ('pathways', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dojo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(blank=True, default='', max_length=200)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, spatial_index=False, srid=4326)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('dormant', 'Dormant'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('icon', models.ImageField(blank=True, help_text='Round icon shown at the top of the dojo page, next to its name.', null=True, upload_to='dojos/')),
                ('tagline', models.TextField(blank=True, default='', help_text='Shown at the top of the dojo page, between the title and the buttons. Supports basic Markdown — # headings, **bold**, *italic*, links, lists.')),
                ('description', models.TextField(blank=True, default='', help_text='Shown further down the dojo page, above the team. Supports basic Markdown — # headings, **bold**, *italic*, links, lists.')),
                ('schedule_description', models.CharField(blank=True, default='', help_text='e.g. "Every 2nd Saturday"', max_length=200)),
                ('min_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('max_age', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('visit_notes', models.TextField(blank=True, default='', help_text='Optional extra info for the Visit us section — parking, entrance, accessibility, whatever this chapter needs to add. Supports basic Markdown — # headings, **bold**, *italic*, links, lists.')),
                ('created_by', models.ForeignKey(blank=True, help_text='The approved champion who created this dojo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='geo.municipality')),
                ('pathways', models.ManyToManyField(blank=True, help_text='The pathways this dojo provides (optional). New events pre-select these.', related_name='dojos', to='pathways.pathway')),
                ('province', models.ForeignKey(blank=True, limit_choices_to={'kind': 'province'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dojos', to='geo.administrativeboundary')),
            ],
        ),
        migrations.CreateModel(
            name='DojoMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('champion', 'Champion'), ('mentor', 'Mentor'), ('youth_mentor', 'Youth mentor')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('active', 'Active'), ('dormant', 'Dormant')], default='active', max_length=10)),
                ('joined_at', models.DateTimeField(blank=True, help_text='When this membership (last) became active.', null=True)),
                ('left_at', models.DateTimeField(blank=True, help_text='When it became dormant; empty while active.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(blank=True, help_text='The champion/mentor who accepted or declined a join request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dojo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dojos.dojo')),
                ('promoted_by', models.ForeignKey(blank=True, help_text='Youth mentors only: the champion/mentor membership that promoted them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dojos.dojomembership')),
                ('requested_by', models.ForeignKey(blank=True, help_text='Who asked (the mentor themselves) or added them (a champion/mentor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dojo_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('dojo', 'user'), name='unique_membership_per_dojo')],
            },
        ),
    ]
