# Generated by Django 6.1.1 on 2026-09-22 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='email',
            field=models.EmailField(blank=True, default='', help_text='Shown on their team detail page, if set.', max_length=254),
        ),
    ]
