# Generated by Django 6.1.1 on 2026-09-25 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='kind',
            field=models.CharField(choices=[('dojo', 'Dojo'), ('organisation', 'Organisation')], default='dojo', help_text="Organisation: runs the organisation's own events. Never shown in the dojo finder or as a dojo page; its events say “Organised by” instead of linking to it.", max_length=12),
        ),
    ]
