# Generated by Django 6.1.1 on 2026-09-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0002_mentor_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='quote',
        ),
        migrations.RemoveField(
            model_name='dojo',
            name='quote_author',
        ),
        migrations.AddField(
            model_name='dojo',
            name='tagline',
            field=models.TextField(blank=True, default='', help_text='Shown at the top of the dojo page, between the title and the buttons. Supports basic Markdown — # headings, **bold**, *italic*, links, lists.'),
        ),
        migrations.AlterField(
            model_name='dojo',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Shown further down the dojo page, above the team. Supports basic Markdown — # headings, **bold**, *italic*, links, lists.'),
        ),
    ]
