# Generated by Django 6.1.1 on 2026-09-25 18:56

import dojos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0002_dojo_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='languages',
            field=models.JSONField(default=dojos.models.default_dojo_languages, help_text='Language codes from LANGUAGES, main language first, e.g. ["nl-be", "fr-be"].'),
        ),
        migrations.AddField(
            model_name='dojo',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='The texts in the dojo\'s other languages: {"fr-be": {"field": "text"}}. The normal fields hold the main language. Edited on the dojo\'s dashboard pages.'),
        ),
    ]
