# Generated by Django 6.1.1 on 2026-09-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0003_remove_dojo_quote_remove_dojo_quote_author_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='visit_notes',
            field=models.TextField(blank=True, default='', help_text='Optional extra info for the Visit us section — parking, entrance, accessibility, whatever this chapter needs to add. Supports basic Markdown — # headings, **bold**, *italic*, links, lists.'),
        ),
    ]
