# Generated by Django 6.1.1 on 2026-09-30 22:36

import core.uploads
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0004_dojo_languages_by_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dojo',
            name='icon',
            field=core.uploads.UploadedImageField(blank=True, help_text='Round icon shown at the top of the dojo page, next to its name.', max_side=512, null=True, upload_to='dojos/'),
        ),
    ]
