# Generated by Django 6.1.1 on 2026-09-22 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0004_dojo_visit_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='icon',
            field=models.ImageField(blank=True, help_text='Round icon shown at the top of the dojo page, next to its name.', null=True, upload_to='dojos/'),
        ),
    ]
