# Generated by Django 6.1.1 on 2026-09-22 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_helperaccount'),
        ('dojos', '0005_dojo_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='mentor',
            name='child_account',
            field=models.OneToOneField(blank=True, help_text="A ninja's own login — only meaningful once they've been promoted to CHAMPION.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profile', to='accounts.childaccount'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='guardian_account',
            field=models.OneToOneField(blank=True, help_text="A parent helping out at their own child's dojo.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profile', to='accounts.guardian'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='helper_account',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profile', to='accounts.helperaccount'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Uncheck to opt this person out of the public team pages.'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='owner_account',
            field=models.OneToOneField(blank=True, help_text="Required for the CHAMPION/Lead Coach mentor — must be this mentor's dojo's own owner login.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profile', to='accounts.dojoowner'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='role',
            field=models.CharField(choices=[('champion', 'Lead Coach'), ('ninja', 'Ninja mentor'), ('volunteer', 'Volunteer mentor'), ('board', 'Board member')], max_length=20),
        ),
    ]
