# Generated by Django 6.1.1 on 2026-09-22 21:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_helperaccount'),
        ('dojos', '0006_mentor_child_account_mentor_guardian_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='owner_account',
            field=models.OneToOneField(blank=True, help_text="Required for the LEAD_COACH mentor — must be this mentor's dojo's own owner login.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profile', to='accounts.dojoowner'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='role',
            field=models.CharField(choices=[('lead_coach', 'Lead Coach'), ('champion', 'Dojo champion'), ('ninja', 'Ninja mentor'), ('volunteer', 'Volunteer mentor'), ('board', 'Board member')], max_length=20),
        ),
    ]
