# Generated by Django 6.1.1 on 2026-09-23 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_background_check_expires_at_and_more'),
        ('dojos', '0007_alter_mentor_owner_account_alter_mentor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='helper_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profiles', to='accounts.helperaccount'),
        ),
        migrations.AddConstraint(
            model_name='mentor',
            constraint=models.UniqueConstraint(fields=('dojo', 'helper_account'), name='unique_helper_per_dojo'),
        ),
    ]
