# Generated by Django 6.1.1 on 2026-09-23 22:49

import django.db.models.deletion
from django.db import migrations, models


def backfill_lead_coaches(apps, schema_editor):
    """Every owned dojo gets its owner as Lead Coach — the same rule
    Dojo.sync_lead_coach applies on save, which historical models don't run."""
    Dojo = apps.get_model("dojos", "Dojo")
    Mentor = apps.get_model("dojos", "Mentor")
    for dojo in Dojo.objects.exclude(owner=None).select_related("owner"):
        Mentor.objects.filter(dojo=dojo, role="lead_coach").exclude(owner_account_id=dojo.owner_id).update(
            role="volunteer", owner_account=None,
        )
        if not Mentor.objects.filter(dojo=dojo, role="lead_coach").exists():
            owner = dojo.owner
            full_name = f"{owner.first_name} {owner.last_name}".strip()
            Mentor.objects.create(
                dojo=dojo, role="lead_coach", owner_account=owner,
                name=full_name or owner.username, email=owner.email,
            )


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_background_check_expires_at_and_more'),
        ('dojos', '0008_mentor_helper_account_foreignkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='owner_account',
            field=models.ForeignKey(blank=True, help_text="Required for the LEAD_COACH mentor — must be this mentor's dojo's own owner login. Set automatically from the dojo's owner.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mentor_profiles', to='accounts.dojoowner'),
        ),
        migrations.AddConstraint(
            model_name='mentor',
            constraint=models.UniqueConstraint(fields=('dojo', 'owner_account'), name='unique_owner_profile_per_dojo'),
        ),
        migrations.RunPython(backfill_lead_coaches, migrations.RunPython.noop),
    ]
