# Generated by Django 6.1.1 on 2026-09-24 05:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0009_mentor_owner_account_foreignkey'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='child_account',
            field=models.OneToOneField(blank=True, help_text="A ninja's own login — only meaningful once they've been promoted to CHAMPION.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ninja_mentor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='guardian_account',
            field=models.OneToOneField(blank=True, help_text="A parent helping out at their own child's dojo.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guardian_mentor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
