# Generated by Django 6.1.1 on 2026-09-24 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0010_redesign_guardianship'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DojoMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('champion', 'Champion'), ('mentor', 'Mentor'), ('youth_mentor', 'Youth mentor')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('active', 'Active'), ('dormant', 'Dormant')], default='active', max_length=10)),
                ('joined_at', models.DateTimeField(blank=True, help_text='When this membership (last) became active.', null=True)),
                ('left_at', models.DateTimeField(blank=True, help_text='When it became dormant; empty while active.', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='mentor',
            name='unique_helper_per_dojo',
        ),
        migrations.RemoveConstraint(
            model_name='mentor',
            name='unique_owner_profile_per_dojo',
        ),
        migrations.RemoveField(
            model_name='dojo',
            name='owner',
        ),
        migrations.AddField(
            model_name='dojo',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The approved champion who created this dojo.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dojo',
            name='status',
            # Existing dojos are real, running dojos: they start out active.
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('dormant', 'Dormant'), ('archived', 'Archived')], default='active', max_length=10),
        ),
        # From here on a new dojo starts as a draft (DATA_MODEL.md §10).
        migrations.AlterField(
            model_name='dojo',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('dormant', 'Dormant'), ('archived', 'Archived')], default='draft', max_length=10),
        ),
        migrations.AddField(
            model_name='dojomembership',
            name='decided_by',
            field=models.ForeignKey(blank=True, help_text='The champion/mentor who accepted or declined a join request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dojomembership',
            name='dojo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='dojos.dojo'),
        ),
        migrations.AddField(
            model_name='dojomembership',
            name='promoted_by',
            field=models.ForeignKey(blank=True, help_text='Youth mentors only: the champion/mentor membership that promoted them.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='dojos.dojomembership'),
        ),
        migrations.AddField(
            model_name='dojomembership',
            name='requested_by',
            field=models.ForeignKey(blank=True, help_text='Who asked (the mentor themselves) or added them (a champion/mentor).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='dojomembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dojo_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='child_account',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='dojo',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='guardian_account',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='helper_account',
        ),
        migrations.RemoveField(
            model_name='mentor',
            name='owner_account',
        ),
        migrations.AddConstraint(
            model_name='dojomembership',
            constraint=models.UniqueConstraint(fields=('dojo', 'user'), name='unique_membership_per_dojo'),
        ),
    ]
