# Generated by Django 6.1.1 on 2026-09-24 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0011_redesign_dojo_team'),
        ('events', '0010_redesign_dojo_team'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mentor',
        ),
    ]
