# Generated by Django 6.1.1 on 2026-09-24 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0012_redesign_dojo_team'),
        ('pathways', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='pathways',
            field=models.ManyToManyField(blank=True, help_text='The pathways this dojo provides (optional). New events pre-select these.', related_name='dojos', to='pathways.pathway'),
        ),
    ]
