# Generated by Django 6.1.1 on 2026-09-30 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CapacitySample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taken_on', models.DateField(unique=True)),
                ('taken_at', models.DateTimeField()),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['-taken_on'],
            },
        ),
    ]
