# Generated by Django 6.1.1 on 2026-10-02 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


MOVED = ("segment", "segmentgroup", "segmentrule", "campaign", "journey", "journeydelivery")


def move_content_types(apps, schema_editor):
    """The moved models keep their content types (and with them their
    permissions and audit-log entries): renamed, not created anew."""
    ContentType = apps.get_model("contenttypes", "ContentType")
    for model in MOVED:
        if not ContentType.objects.filter(app_label="campaigns", model=model).exists():
            ContentType.objects.filter(app_label="mailing", model=model).update(app_label="campaigns")


def move_content_types_back(apps, schema_editor):
    ContentType = apps.get_model("contenttypes", "ContentType")
    ContentType.objects.filter(app_label="campaigns", model__in=MOVED).update(app_label="mailing")


class Migration(migrations.Migration):
    """Campaigns, segments and journeys move from mailing (2 October 2026):
    only Django's state moves, the tables keep their names and their data
    (db_table), so nothing changes in the database but the content types."""

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('dojos', '0005_alter_dojo_icon'),
        ('mailing', '0015_campaign_queued_up_to'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'mailing_segment',
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('service', 'Account and security'), ('registration', 'Session bookings'), ('reminder', 'Reminders'), ('dojo_news', 'News from your dojo'), ('volunteer', 'Volunteering'), ('newsletter', 'Newsletter and campaigns')], default='dojo_news', max_length=20)),
                ('template_key', models.CharField(max_length=100)),
                ('context', models.JSONField(blank=True, default=dict)),
                ('cooldown_days', models.PositiveIntegerField(default=365, help_text="Someone who got it doesn't get it again for this many days.")),
                ('is_active', models.BooleanField(default=False)),
                ('activated_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journeys', to='campaigns.segment')),
            ],
            options={
                'db_table': 'mailing_journey',
            },
        ),
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translations', models.JSONField(blank=True, default=dict, help_text='The texts in the dojo\'s other languages: {"fr-be": {"field": "text"}}. The normal fields hold the main language. Edited on the dojo\'s dashboard pages.')),
                ('segment_snapshot', models.JSONField(blank=True, null=True)),
                ('audience', models.CharField(blank=True, help_text="A dojo mailing's audience (mailing.dojo_audiences).", max_length=30)),
                ('audience_params', models.JSONField(blank=True, default=dict)),
                ('subject', models.CharField(blank=True, help_text="A dojo mailing's subject, main language.", max_length=150)),
                ('message', models.TextField(blank=True, help_text="A dojo mailing's text (plain text), main language.")),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('service', 'Account and security'), ('registration', 'Session bookings'), ('reminder', 'Reminders'), ('dojo_news', 'News from your dojo'), ('volunteer', 'Volunteering'), ('newsletter', 'Newsletter and campaigns')], default='newsletter', max_length=20)),
                ('template_key', models.CharField(help_text='EmailTemplate.key; each recipient gets the version in their language.', max_length=100)),
                ('context', models.JSONField(blank=True, default=dict, help_text='Extra template variables for this campaign, e.g. {"signup_url": "https://…"}.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('queued', 'Queued'), ('sending', 'Sending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scheduled_at', models.DateTimeField(blank=True, help_text="Leave empty to send as soon as it's launched.", null=True)),
                ('launched_at', models.DateTimeField(blank=True, editable=False, null=True)),
                ('queued_at', models.DateTimeField(blank=True, editable=False, help_text="When every recipient's mail was queued.", null=True)),
                ('queued_up_to', models.PositiveBigIntegerField(default=0, editable=False, help_text='The last account id whose mail is queued (the mail is queued in chunks, in id order).')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('dojo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='dojos.dojo')),
                ('launched_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('segment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='campaigns.segment')),
            ],
            options={
                'db_table': 'mailing_campaign',
            },
        ),
        migrations.CreateModel(
            name='SegmentGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('and', 'AND'), ('or', 'OR')], default='and', max_length=3)),
                ('scope', models.CharField(choices=[('user', 'Accounts'), ('ninja', 'Parents of a child who …')], default='user', max_length=5)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='campaigns.segmentgroup')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='campaigns.segment')),
            ],
            options={
                'db_table': 'mailing_segmentgroup',
            },
        ),
        migrations.CreateModel(
            name='SegmentRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attribute', models.CharField(max_length=100)),
                ('operator', models.CharField(max_length=50)),
                ('value', models.JSONField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='campaigns.segmentgroup')),
            ],
            options={
                'db_table': 'mailing_segmentrule',
            },
        ),
        migrations.CreateModel(
            name='JourneyDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('email', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='mailing.emailmessage')),
                ('journey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='campaigns.journey')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mailing_journeydelivery',
                'indexes': [models.Index(fields=['journey', 'user', 'created_at'], name='mailing_journey_delivery_idx')],
            },
        ),
            ],
            database_operations=[],
        ),
        migrations.RunPython(move_content_types, move_content_types_back),
    ]
