# Generated by Django 6.1.1 on 2026-10-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='audience',
            field=models.CharField(blank=True, help_text="A dojo mailing's audience (campaigns.dojo_audiences).", max_length=30),
        ),
    ]
