# Generated by Django 6.1.1 on 2026-09-22 15:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeBoundary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('country', 'Country'), ('province', 'Province')], db_index=True, max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('boundary', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(db_index=True, max_length=10)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('center', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
    ]
