# Generated by Django 6.1.1 on 2026-09-24 06:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_testimonial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganisationTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('position', models.CharField(help_text='e.g. "Member of the board", "Volunteer coordinator"', max_length=200)),
                ('email', models.EmailField(blank=True, default='', help_text='Shown on their detail page, if set.', max_length=254)),
                ('bio', models.TextField(blank=True, default='')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('focus_areas', models.CharField(blank=True, default='', help_text='Comma-separated, e.g. "Partnerships, Events"', max_length=300)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower comes first.')),
                ('is_public', models.BooleanField(default=True)),
                ('account', models.ForeignKey(blank=True, help_text="Optional: the person's own account, if they have one.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
