# Generated by Django 6.1.1 on 2026-09-24 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'ordering': ['-date', '-id']},
        ),
    ]
