# Generated by Django 6.1.1 on 2026-09-25 15:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_announcement_options'),
        ('events', '0007_event_external_registration_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placement', models.CharField(choices=[('homepage_hero', 'Homepage: large card under the introduction'), ('event_list_top', 'Events page: pinned above the list'), ('upcoming_first', 'Homepage: first in Upcoming sessions'), ('dojo_finder_banner', 'Dojo finder: banner above the results')], max_length=20)),
                ('rank', models.PositiveSmallIntegerField(default=0, help_text='Lower shows first within a placement.')),
                ('starts_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('ends_at', models.DateTimeField(blank=True, help_text='Empty: the promotion ends when the event starts.', null=True)),
                ('title', models.CharField(blank=True, default='', help_text="Optional: replaces the event's name.", max_length=200)),
                ('image', models.ImageField(blank=True, help_text="Optional: replaces the event's banner.", null=True, upload_to='promotions/')),
                ('text', models.CharField(blank=True, default='', help_text='Optional short pitch.', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='events.event')),
            ],
            options={
                'ordering': ['placement', 'rank', 'starts_at'],
            },
        ),
    ]
