# Generated by Django 6.1.1 on 2026-09-25 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='translations',
            field=models.JSONField(blank=True, default=dict, help_text='The texts in the dojo\'s other languages: {"fr-be": {"field": "text"}}. The normal fields hold the main language. Edited on the dojo\'s dashboard pages.'),
        ),
    ]
