# Generated by Django 6.1.1 on 2026-09-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_organisation_content_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True, default='', verbose_name='website')),
                ('logo', models.ImageField(blank=True, help_text="Optional. Without a logo, the sponsor's name is shown.", null=True, upload_to='sponsors/')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Lower comes first.')),
                ('is_public', models.BooleanField(default=True, help_text='Uncheck to hide it from the homepage.', verbose_name='shown')),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
