# Generated by Django 6.1.1 on 2026-09-30 22:36

import core.uploads
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_sponsor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisationteammember',
            name='photo',
            field=core.uploads.UploadedImageField(blank=True, max_side=512, null=True, upload_to='team/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=core.uploads.UploadedImageField(blank=True, help_text="Optional: replaces the event's banner.", max_side=1600, null=True, upload_to='promotions/'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=core.uploads.UploadedImageField(blank=True, help_text="Optional. Without a logo, the sponsor's name is shown.", max_side=800, null=True, upload_to='sponsors/'),
        ),
    ]
