"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import importlib.util
import sys
from pathlib import Path

import environ
from celery.schedules import crontab
from django.utils.csp import CSP

env = environ.Env(
    DEBUG=(bool, False),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=False)

# django-silk: request and SQL profiling, a development tool only
# (requirements-dev.txt, never installed in production). On while DEBUG is on
# and the package is installed; SILK=false switches it off, SILK=true on with
# DEBUG off too (the devcontainer's production-like run, to profile it there).
# Profile a function with core.profiling.profile, never silk directly.
SILK_ENABLED = env.bool("SILK", default=DEBUG) and importlib.util.find_spec("silk") is not None

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS")

# Set by the .devcontainer workspace (COOKIE_DOMAIN env var) so session/CSRF
# cookies scope correctly to coolregistration.localhost behind the nginx
# proxy; unset (None) for plain host-based `runserver` dev, which is fine.
COOKIE_DOMAIN = env("COOKIE_DOMAIN")
SESSION_COOKIE_DOMAIN = COOKIE_DOMAIN
CSRF_COOKIE_DOMAIN = COOKIE_DOMAIN
# Sessions are read from the cache's Redis and written through to MySQL
# (CAPACITY.md, "Caching"): no session query on a logged-in request, and an
# emptied cache or an evicted key logs nobody out.
SESSION_ENGINE = "django.contrib.sessions.backends.cached_db"

# HTTPS (MAINTENANCE.md, security log). TLS ends at the proxy in front of
# Django (Level27's in production, nginx in the devcontainer), which says so in
# X-Forwarded-Proto; that proxy must set the header itself and never pass on a
# client's. The rest comes from the environment, so production can turn on the
# redirect and raise HSTS step by step (1 hour, 1 day, then 1 year) in its .env:
# HSTS can't be taken back from a browser that has seen it. `manage.py check
# --deploy` warns while any of them is off.
SECURE_PROXY_SSL_HEADER = (
    ("HTTP_X_FORWARDED_PROTO", "https") if env.bool("TRUST_X_FORWARDED_PROTO", default=True) else None
)
# Off only for a plain-http run on the host (SECURE_COOKIES=false).
SESSION_COOKIE_SECURE = env.bool("SECURE_COOKIES", default=True)
CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool("SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False)
SECURE_HSTS_PRELOAD = False
# Not on the browsers' HSTS preload list, on purpose: leaving it takes months.
SILENCED_SYSTEM_CHECKS = ["security.W021"]

# Content-Security-Policy (Django's own ContentSecurityPolicyMiddleware): scripts
# only from our own static files, or an inline <script nonce="{{ csp_nonce }}">;
# never inline event handlers (onclick=...: use data-confirm, data-autosubmit or
# data-action, handled in bundle.js) and never eval (htmx's allowEval is off, so
# no hx-on). Inline styles stay allowed: there are hundreds of style="..."
# attributes, and styles can't run code. Images also from OpenStreetMap's tiles
# (the admin's map widget). CSP_REPORT_ONLY=true sends it as report-only, to see
# what would break without blocking it.
CONTENT_SECURITY_POLICY = {
    "default-src": [CSP.SELF],
    "script-src": [CSP.SELF, CSP.NONCE],
    "style-src": [CSP.SELF, CSP.UNSAFE_INLINE],
    "img-src": [CSP.SELF, "data:", "blob:", "https://tile.openstreetmap.org"],
    "font-src": [CSP.SELF],
    "connect-src": [CSP.SELF],
    "object-src": [CSP.NONE],
    "base-uri": [CSP.SELF],
    "form-action": [CSP.SELF],
    "frame-ancestors": [CSP.NONE],
}
if env.bool("CSP_REPORT_ONLY", default=False):
    SECURE_CSP_REPORT_ONLY = CONTENT_SECURITY_POLICY
else:
    SECURE_CSP = CONTENT_SECURITY_POLICY

# Permissions-Policy (django-permissions-policy): switches off the browser
# features the site never uses. Kept for our own pages only: geolocation (the
# dojo finder's "Use my location"), passkeys (Sign-in security and the login),
# fullscreen.
PERMISSIONS_POLICY = {
    "accelerometer": [],
    "autoplay": [],
    "browsing-topics": [],
    "camera": [],
    "display-capture": [],
    "encrypted-media": [],
    "fullscreen": ["self"],
    "geolocation": ["self"],
    "gyroscope": [],
    "hid": [],
    "idle-detection": [],
    "magnetometer": [],
    "microphone": [],
    "midi": [],
    "payment": [],
    "publickey-credentials-create": ["self"],
    "publickey-credentials-get": ["self"],
    "screen-wake-lock": [],
    "serial": [],
    "usb": [],
    "xr-spatial-tracking": [],
}

INTERNAL_IPS = [
    "127.0.0.1",
]


# Show the Debug Toolbar whenever Django's effective DEBUG setting is true.
# Reading django.conf.settings here is intentional: test overrides such as
# override_settings(DEBUG=False) should be respected by the callback.
def _show_debug_toolbar(request):
    from django.conf import settings

    return settings.DEBUG


DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": _show_debug_toolbar,
}


AUTH_USER_MODEL = "accounts.User"
LOGIN_URL = "login"

AUTHENTICATION_BACKENDS = [
    "accounts.backends.EmailOrUsernameBackend",
    "django.contrib.auth.backends.ModelBackend",
]

# Two-step login (DATA_MODEL.md §15, accounts/two_step.py): django-otp holds
# the devices (authenticator app, passkeys, backup codes) and marks a session
# as verified; django-two-factor-auth gives the login in steps, which
# accounts.views.LoginView wraps. Which roles must use it is the
# organisation's sign-in policy (accounts.SignInRequirement, /manage/security/).
LOGIN_REDIRECT_URL = "account_home"
TWO_FACTOR_REMEMBER_COOKIE_AGE = 30 * 24 * 3600  # "Don't ask again on this device for 30 days"
TWO_FACTOR_REMEMBER_COOKIE_SECURE = True
TWO_FACTOR_REMEMBER_COOKIE_DOMAIN = COOKIE_DOMAIN
# The name authenticator apps show next to the code, and passkeys next to the account.
TWO_FACTOR_ISSUER = "CoderDojo Belgium"
TWO_FACTOR_WEBAUTHN_RP_NAME = TWO_FACTOR_ISSUER
# Passkeys are checked against SITE_URL's host and origin, not the request's:
# nginx (and Level27's proxy) terminate TLS, so the request itself looks like http.
TWO_FACTOR_WEBAUTHN_ENTITIES_FORM_MIXIN = "accounts.webauthn_entities.SiteWebauthnEntitiesMixin"
# Ask for the device's PIN or fingerprint when it has one, as passkeys normally do.
TWO_FACTOR_WEBAUTHN_UV_REQUIREMENT = "preferred"

# Outgoing mail. Inside the .devcontainer workspace, EMAIL_HOST is set and
# mail goes to the Mailpit catcher (see .devcontainer/docker-compose.yml);
# outside it (plain host-based `runserver`), EMAIL_HOST is unset and mail
# prints to the console.
EMAIL_HOST = env("EMAIL_HOST")
if EMAIL_HOST:
    EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
    EMAIL_PORT = env("EMAIL_PORT", default=2525)
    EMAIL_HOST_USER = env("EMAIL_HOST_USER")
    EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
    EMAIL_USE_TLS = env("EMAIL_USE_TLS", default=True)
else:
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"

DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL", default="CoderDojo Belgium <no-reply@coderdojobelgium.example>")
# A stuck SMTP connection fails (and the batch is retried) instead of
# blocking the mailing worker.
EMAIL_TIMEOUT = env.int("EMAIL_TIMEOUT", default=30)

# The site's own address, for links in mails (which are rendered in a
# worker, with no request to build absolute URLs from).
# Monitoring (monitoring, CAPACITY.md): /metrics/ answers only with this token
# as a bearer token, and doesn't exist while it's empty. Slow requests are
# logged from METRICS_SLOW_REQUEST_MS on.
METRICS_TOKEN = env("METRICS_TOKEN", default="")
METRICS_ENABLED = env.bool("METRICS_ENABLED", default=True)
METRICS_SLOW_REQUEST_MS = env.int("METRICS_SLOW_REQUEST_MS", default=1000)

SITE_URL = env("SITE_URL", default="https://coolregistration.localhost").rstrip("/")

# The testers' authenticator in the devcontainer (2FAuth, the `otp` service),
# which `manage.py seed_otp_vault` fills with the seeded accounts' app keys.
# Empty everywhere else (production), and the command then does nothing.
OTP_VAULT_URL = env("OTP_VAULT_URL", default="").rstrip("/")

# The mail engine (mailing app, DATA_MODEL.md §11 "Sending pipeline").
MAILING_BATCH_SIZE = env.int("MAILING_BATCH_SIZE", default=20)  # rows per send_email_batch subtask
# Rows in flight (claimed, not yet sent): what the broker holds, first in,
# first out. Two batches is 20 seconds of sending at 6 batches a minute, so mail
# claimed next (a booking confirmation, claimed first by priority) waits that
# long at most; the dispatcher refills every 10 seconds, so sending never
# runs dry. 200 held 100 seconds of batches (CAPACITY.md, finding 8).
MAILING_CLAIM_LIMIT = env.int("MAILING_CLAIM_LIMIT", default=2 * MAILING_BATCH_SIZE)
# Accounts per launch_campaign task: a campaign is queued a chunk at a time, so
# mail queued meanwhile waits for one chunk (a few seconds), not the campaign.
MAILING_CAMPAIGN_CHUNK_SIZE = env.int("MAILING_CAMPAIGN_CHUNK_SIZE", default=200)
# Celery rate limit for send_email_batch (per worker; there is one mailing
# worker). Throughput is at most this many batches times MAILING_BATCH_SIZE.
MAILING_BATCH_RATE_LIMIT = env("MAILING_BATCH_RATE_LIMIT", default="6/m")
MAILING_CLAIM_TIMEOUT_MINUTES = env.int("MAILING_CLAIM_TIMEOUT_MINUTES", default=60)
# Automated mail (mailing.automated).
MAILING_REMINDER_DAYS_BEFORE = 2  # the session reminder goes out this many days before
MAILING_DOJO_NEWS_ACTIVE_DAYS = 365  # a family belongs to a dojo that long after a visit
# A dojo's own mailings to its families (DATA_MODEL.md §25): at most this many
# launched per dojo in any 30 days, and a message at most this long.
MAILING_DOJO_MAILINGS_PER_30_DAYS = 4
MAILING_DOJO_MESSAGE_MAX_LENGTH = 5000

# Bounces (mailing.bounce): the envelope sender of every mail, so bounces land
# in that mailbox. "{id}" is replaced by the EmailMessage id when the mail
# host supports plus-addressing (VERP), e.g. "bounces+{id}@example.org";
# empty sends bounces to DEFAULT_FROM_EMAIL as before.
MAILING_BOUNCE_ADDRESS = env("MAILING_BOUNCE_ADDRESS", default="")
# The mailbox process_bounces reads; empty host = bounce processing is off.
# IMAP in production; POP3 is there for the devcontainer, where Mailpit
# (which only speaks POP3) is the bounce mailbox.
MAILING_BOUNCE_PROTOCOL = env("MAILING_BOUNCE_PROTOCOL", default="imap")
MAILING_BOUNCE_IMAP_HOST = env("MAILING_BOUNCE_IMAP_HOST", default="")
MAILING_BOUNCE_IMAP_PORT = env.int("MAILING_BOUNCE_IMAP_PORT", default=993)
# Plain (no TLS) only for the devcontainer's Mailpit.
MAILING_BOUNCE_IMAP_SSL = env.bool("MAILING_BOUNCE_IMAP_SSL", default=True)
MAILING_BOUNCE_IMAP_USER = env("MAILING_BOUNCE_IMAP_USER", default="")
MAILING_BOUNCE_IMAP_PASSWORD = env("MAILING_BOUNCE_IMAP_PASSWORD", default="")
MAILING_BOUNCE_IMAP_MAILBOX = env("MAILING_BOUNCE_IMAP_MAILBOX", default="INBOX")
MAILING_BOUNCE_IMAP_TIMEOUT = env.int("MAILING_BOUNCE_IMAP_TIMEOUT", default=30)
MAILING_BOUNCE_BATCH = 200  # messages per run, so the periodic worker stays quick
# This many temporary failures (4.x.x) for one address within the window
# block it, like a hard bounce.
MAILING_SOFT_BOUNCE_LIMIT = 3
MAILING_SOFT_BOUNCE_WINDOW_DAYS = 30

# Celery (website/celery.py). Two workers, see DATA_MODEL.md §11
# "Production: two Celery workers under systemd": a `periodic` worker with
# beat embedded runs the jobs beat triggers, and a mailing worker runs
# everything else on the default queue.
CELERY_TIMEZONE = "Europe/Brussels"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

CELERY_RESULT_BACKEND = "django-db"
# Tasks report through the rows they change (EmailMessage.status, ...), not
# through results: without this the 10-second dispatcher alone would write
# thousands of TaskResult rows a day.
CELERY_TASK_IGNORE_RESULT = True

# Redis db 0 is the cache and db 1 the Channels layer: the broker gets its
# own, so a cache.clear() can never drop queued tasks.
CELERY_BROKER_URL = "redis://{host}:{port}/{db}".format(
    host=env("REDIS_HOST", default="127.0.0.1"),
    port=env("REDIS_PORT", default="6379"),
    db=env("CELERY_BROKER_DB", default="2"),
)

# A task is acknowledged only once it's done, so the broker hands out a
# task again if its worker dies halfway. The mail tasks are written to be
# safe to run twice (rows already `sent` are skipped).
CELERY_TASK_ACKS_LATE = True
CELERY_TASK_REJECT_ON_WORKER_LOST = True
CELERY_WORKER_PREFETCH_MULTIPLIER = 1

# Every task beat triggers runs on the `periodic` queue; anything not listed
# here stays on the default queue (the mailing worker).
PERIODIC_QUEUE = "periodic"
CELERY_BEAT_SCHEDULE = {
    "process-mail-bounces": {
        "task": "mailing.tasks.process_bounces",
        "schedule": 5 * 60.0,
        "options": {"expires": 5 * 60},
    },
    "send-pending-emails": {
        "task": "mailing.tasks.send_pending_emails",
        "schedule": 10.0,
        # A worker that was down doesn't come back to a pile of stale runs.
        "options": {"expires": 10},
    },
    "launch-due-campaigns": {
        "task": "mailing.tasks.launch_due_campaigns",
        "schedule": 60.0,
        "options": {"expires": 60},
    },
    "requeue-stuck-emails": {
        "task": "mailing.tasks.requeue_stuck_emails",
        "schedule": 15 * 60.0,
        "options": {"expires": 15 * 60},
    },
    # Time-boxed access to the Django admin (accounts.admin_access, DATA_MODEL.md
    # §23): records the end of access whose 12 hours are up. Short, so on `periodic`.
    "close-admin-access": {
        "task": "accounts.tasks.close_admin_access",
        "schedule": 5 * 60.0,
        "options": {"expires": 5 * 60},
    },
    # Heavier daily jobs run on the default queue (the mailing worker), so
    # they never hold up the 10-second dispatcher: an explicit "queue".
    "session-reminders": {
        "task": "mailing.tasks.send_session_reminders",
        "schedule": crontab(hour=9, minute=0),
        "options": {"queue": "celery", "expires": 6 * 3600},
    },
    # Before the day's mail jobs, so segments and the dashboards see fresh figures.
    "rebuild-engagement": {
        "task": "events.tasks.rebuild_engagement",
        "schedule": crontab(hour=3, minute=0),
        "options": {"queue": "celery", "expires": 6 * 3600},
    },
    # After the nightly engagement rebuild, so "became at risk" is fresh.
    "journeys": {
        "task": "mailing.tasks.run_journeys",
        "schedule": crontab(hour=18, minute=0),
        "options": {"queue": "celery", "expires": 6 * 3600},
    },
    "new-sessions-digest": {
        "task": "mailing.tasks.announce_new_sessions",
        "schedule": crontab(hour=17, minute=0),
        "options": {"queue": "celery", "expires": 6 * 3600},
    },
    # Reminder mails and deletions for accounts unused for two years, the
    # audit log and expired sessions (privacy.retention). Daytime, since it
    # mails families.
    "retention": {
        "task": "privacy.tasks.apply_retention",
        "schedule": crontab(hour=10, minute=0),
        "options": {"queue": "celery", "expires": 6 * 3600},
    },
    # Background checks (applications.reminders, DATA_MODEL.md §21): the
    # 30-day expiry reminder, and reviewers told about documents waiting.
    "background-check-expiry-reminders": {
        "task": "applications.tasks.remind_expiring_background_checks",
        "schedule": crontab(hour=10, minute=30),
        "options": {"queue": "celery", "expires": 6 * 3600},
    },
    "background-checks-waiting": {
        "task": "applications.tasks.mail_background_check_reviewers",
        "schedule": crontab(hour=9, minute=0),
        "options": {"queue": "celery", "expires": 6 * 3600},
    },
    # The day's capacity sample (monitoring, CAPACITY.md): a few quick
    # reads of table sizes and counters, so on `periodic`.
    "capacity-sample": {
        "task": "monitoring.tasks.record_capacity_sample",
        "schedule": crontab(hour=2, minute=30),
        "options": {"expires": 6 * 3600},
    },
}
CELERY_TASK_ROUTES = {
    entry["task"]: {"queue": PERIODIC_QUEUE}
    for entry in CELERY_BEAT_SCHEDULE.values()
    if "queue" not in entry.get("options", {})
}

# Application definition

INSTALLED_APPS = [
    # Must be first — this is what makes `manage.py runserver` transparently
    # serve over ASGI (via Daphne) instead of the default WSGI dev server,
    # which is what lets notifications/consumers.py's WebSocket route work
    # with zero changes to how the devcontainer/docs already invoke runserver.
    "daphne",
    # Django's admin with pages.admin_site.AdminSite as admin.site: it applies
    # the organisation's sign-in policy (accounts.sign_in) to /admin/.
    "pages.admin_apps.AdminConfig",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.gis",
    "debug_toolbar",
    "core",
    "geo",
    "accounts",
    "dojos",
    "pathways",
    "events",
    "content",
    "applications",
    "notifications",
    "django_celery_results",
    "mailing",
    # Campaigns, segments, journeys and a dojo's own mail, on top of the mail
    # engine above (CODING_STANDARDS.md, "Layers").
    "campaigns",
    "django_celery_beat",
    "ninja",
    "oauth2_provider",
    "privacy",
    "monitoring",
    "api",
    # The homepage, /manage/'s landing, the audit log page and the health
    # check, assembled from the apps above (CODING_STANDARDS.md, "Layers").
    "pages",
    "auditlog",
    # Two-step login (DATA_MODEL.md §15). No phone, email or YubiKey plugins.
    "django_otp",
    "django_otp.plugins.otp_totp",
    "django_otp.plugins.otp_static",
    "formtools",
    "two_factor",
    "two_factor.plugins.webauthn",
    # Django's own form templates, last: the project's templates override them
    # (core/templates/django/forms/, see FORM_RENDERER).
    "django.forms",
]

# The site's forms render through core/forms/field.html and core/forms/form.html
# (core/forms.py): one layout for every field, and the site's input classes.
FORM_RENDERER = "core.forms.SiteFormRenderer"

MIDDLEWARE = [
    # First, so its timing covers the whole stack (monitoring, CAPACITY.md).
    "monitoring.middleware.RequestMetricsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
    "django_permissions_policy.PermissionsPolicyMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # Must come after SessionMiddleware, before CommonMiddleware, per
    # https://docs.djangoproject.com/en/6.1/topics/i18n/translation/#how-django-discovers-language-preference
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Marks request.user as verified (is_verified()) when the session passed
    # two-step login; needs request.user.
    "django_otp.middleware.OTPMiddleware",
    # Records who made each audit-log entry (DATA_MODEL.md §14); needs request.user.
    "core.audit.AuditlogMiddleware",
    "accounts.middleware.ForcePasswordChangeMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    # Sends an account below its role's sign-in requirement to set up
    # two-step login (accounts.sign_in); after OTPMiddleware and
    # MessageMiddleware (it leaves a message when it logs someone out).
    "accounts.middleware.SignInRequirementMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "debug_toolbar.middleware.DebugToolbarMiddleware",
]

if SILK_ENABLED:
    INSTALLED_APPS.append("silk")
    # First, so the time it measures covers the whole request.
    MIDDLEWARE.insert(0, "silk.middleware.SilkyMiddleware")
    # cProfile for the functions wrapped in core.profiling.profile.
    SILKY_PYTHON_PROFILER = True
    # /silk/ shows whole requests, other people's posted passwords included:
    # staff logins only (privacy/privacy.py classifies what it stores).
    SILKY_AUTHENTICATION = True
    SILKY_AUTHORISATION = True

ROOT_URLCONF = "website.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                # csp_nonce, for <script nonce="{{ csp_nonce }}"> (SECURE_CSP above).
                "django.template.context_processors.csp",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "accounts.context_processors.user_roles",
                "accounts.context_processors.sign_in_notice",
                "core.context_processors.organisation_contact",
            ],
        },
    },
]

WSGI_APPLICATION = "website.wsgi.application"
# What `daphne` (see INSTALLED_APPS) actually serves `runserver` through —
# website/asgi.py routes plain HTTP requests through Django as usual and
# WebSocket connections (notifications/routing.py) through Channels.
# WSGI_APPLICATION is left in place for any WSGI-only tooling; it's not
# what's actually handling requests once daphne is installed.
ASGI_APPLICATION = "website.asgi.application"


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
#
# Defaults below match the standalone host-side MySQL container used before
# the .devcontainer setup existed:
# docker run --name mysql-coderdojo   -e MYSQL_DATABASE=coderdojo   -e MYSQL_USER=coderdojo   -e MYSQL_PASSWORD=coderdojo   -e MYSQL_ROOT_PASSWORD=rootpassword   -p 13306:3306   -d mysql
# Inside the .devcontainer workspace, DB_* env vars (see docker-compose.yml)
# point this at the `db` service instead.

DATABASES = {
    "default": {
        "ENGINE": "django.contrib.gis.db.backends.mysql",
        "NAME": env("DB_NAME", default="coderdojo"),
        "USER": env("DB_USER", default="coderdojo"),
        "PASSWORD": env("DB_PASSWORD", default="coderdojo"),
        "HOST": env("DB_HOST", default="127.0.0.1"),
        "PORT": env("DB_PORT", default="13306"),
    }
}

# Cache / Redis. Inside the .devcontainer workspace, REDIS_HOST points at
# the `redis` service; outside it, this falls back to a local Redis on the
# default port (or just won't connect until one exists — the cache is not
# required for the app to boot).
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        # REDIS_CACHE_DB (and REDIS_CHANNELS_DB, CELERY_BROKER_DB) only move for
        # a separate run on the same Redis, e.g. a load test (CAPACITY.md).
        "LOCATION": "redis://{host}:{port}/{db}".format(
            host=env("REDIS_HOST", default="127.0.0.1"),
            port=env("REDIS_PORT", default="6379"),
            db=env("REDIS_CACHE_DB", default="0"),
        ),
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            # Cache reads/writes fail open rather than raising — without a
            # local Redis (e.g. host-based dev/tests outside the
            # devcontainer, where REDIS_HOST defaults to 127.0.0.1 with
            # nothing listening), every cache.get()/set() would otherwise
            # hard-error instead of just skipping the cache.
            "IGNORE_EXCEPTIONS": True,
            "SOCKET_CONNECT_TIMEOUT": 2,
            "SOCKET_TIMEOUT": 2,
        },
    }
}

# `manage.py test` gets its own Redis database: tests fill the cache with
# their own rows (the homepage's Upcoming sessions, the dojo finder's
# default list) and clear it, which would otherwise show up in, or wipe,
# the running dev server's cache. Still Redis, not LocMemCache, because
# code under test uses Redis-only features (cache.lock in campaigns.services).
if len(sys.argv) > 1 and sys.argv[1] == "test":
    CACHES["default"]["LOCATION"] = CACHES["default"]["LOCATION"].rsplit("/", 1)[0] + "/3"

# The test results as JUnit XML when the tests run with
# `--testrunner xmlrunner.extra.djangotestrunner.XMLTestRunner` (unittest-xml-reporting,
# requirements-dev.txt): the Tests workflow does, for its summary and the failed
# tests marked on the code (.github/scripts/test_report.py). Plain runs ignore these.
TEST_OUTPUT_DIR = env("TEST_OUTPUT_DIR", default="test-results")
TEST_OUTPUT_FILE_NAME = "junit.xml"

# Channels' backing store for notifications/consumers.py — same Redis
# instance as CACHES above (same REDIS_HOST/REDIS_PORT), but db 1 rather
# than 0 so channel-layer keys never collide with cache keys. Unlike the
# cache, there's no IGNORE_EXCEPTIONS-style fail-open option here: without
# Redis, group_send() in notifications.services.notify() will raise, which
# is caught there rather than here (a live push failing shouldn't break
# the action that triggered the notification; the DB row is what matters).
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {
            "hosts": [
                {
                    "address": "redis://{host}:{port}/{db}".format(
                        host=env("REDIS_HOST", default="127.0.0.1"),
                        port=env("REDIS_PORT", default="6379"),
                        db=env("REDIS_CHANNELS_DB", default="1"),
                    ),
                    # Longer than channels_redis's 5-second blocking wait for
                    # the next message (RedisChannelLayer.brpop_timeout).
                    # redis-py 8 defaults to a 5-second socket timeout, which
                    # makes that wait time out and closes every notification
                    # socket a few seconds after it opens.
                    "socket_timeout": 10,
                }
            ],
        },
    },
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = "en-us"

# Offered in the menu's language switcher (django.views.i18n.set_language,
# see website/urls.py) and as the mail language. The site's texts are
# translated in locale/<nl_BE|fr_BE>/LC_MESSAGES/django.po (see CLAUDE.md,
# "i18n"); German was dropped until German texts can be checked.
LANGUAGES = [
    ("en-us", "English"),
    ("nl-be", "Nederlands (België)"),
    ("fr-be", "Français (Belgique)"),
]
LOCALE_PATHS = [BASE_DIR / "locale"]
# The languages the organisation writes its own content in (pathways, FAQs,
# badges, belts, team listing, promotions; core.content_languages), main
# language first: the normal fields hold it, the others are translations
# edited in the admin. A dojo picks its own (Dojo.languages).
ORGANISATION_LANGUAGES = ["en-us", "nl-be", "fr-be"]

# CoderDojo Belgium's own contact details (coderdojobelgium.be, September
# 2026): the footer and the Contact page (core.context_processors).
ORGANISATION_CONTACT = {
    "name": "CoderDojo Belgium",
    "legal_name": "CoderDojo Belgium vzw",
    "email": "info@coderdojobelgium.be",
    "office": ["Liersesteenweg 4", "2800 Mechelen"],
    "registered_office": ["François Rigasquare 16", "1030 Schaarbeek"],
    "company_number": "0523.889.476",
    "website": "https://coderdojobelgium.be",
    "facebook": "https://www.facebook.com/CoderDojoBelgiumvzw",
    "instagram": "https://www.instagram.com/coderdojobelgium/",
    "linkedin": "https://www.linkedin.com/company/coderdojo-belgium/",
}

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [BASE_DIR / "static"]

# Where collectstatic gathers the static files for a web server to serve. Only
# set in the devcontainer (STATIC_ROOT env var), where start.sh collects them
# for nginx when DEBUG is off; production doesn't set it (scripts/deploy.sh
# skips collectstatic then).
STATIC_ROOT = env("STATIC_ROOT", default=None)

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

# Background check documents (criminal record extracts) are sensitive and
# must never be reachable via a public URL, unlike MEDIA_ROOT above which
# website/urls.py serves directly under DEBUG. This directory has no
# corresponding url() — the only way to read a file here is through the
# permission-gated view in applications.views. See applications.storage.
PRIVATE_MEDIA_ROOT = BASE_DIR / "private_media"


# Audit log (django-auditlog, DATA_MODEL.md §14): who changed what, and who
# viewed a child's health notes or a criminal-record extract (core.audit).
# The recorded models are core.audit.RECORDED (registered from
# CoreConfig.ready); every other model is listed with its reason in
# core.tests.AuditLogCoverageTests. Shown only in the Django admin,
# read-only, to the organisation's admin role.
AUDITLOG_INCLUDE_ALL_MODELS = False
AUDITLOG_DISABLE_ON_RAW_SAVE = True  # fixtures aren't history
AUDITLOG_DISABLE_REMOTE_ADDR = True  # no IP addresses: every entry has its account, nginx logs the rest
# Changes as text: with JSON, auditlog 3.4.1 compares file fields as
# objects and records an empty photo as a change on every save.
AUDITLOG_STORE_JSON_CHANGES = False
AUDITLOG_MASK_CALLABLE = "core.audit.mask"  # the default keeps half the value
AUDITLOG_USE_FK_STRING_REPRESENTATION = False  # links as ids, not names: less personal data in the log

# The API (api/, DATA_MODEL.md §13): OAuth 2.0 client credentials only, for
# the API clients a dojo's champion makes (api.models.DojoApiClient). A
# client may only ask for the scopes it was given (api.scopes); tokens last
# an hour; client secrets are stored hashed (django-oauth-toolkit's default).
OAUTH2_PROVIDER = {
    "SCOPES": {
        "attendance:read": "See the dojo's sessions and who has a place",
        "attendance:write": "Mark who came to the dojo's sessions",
    },
    "SCOPES_BACKEND_CLASS": "api.scopes.ClientScopes",
    "ACCESS_TOKEN_EXPIRE_SECONDS": 3600,
    # RFC 9700 (OAuth 2.0 Security Best Current Practice), ahead of the
    # toolkit's 4.0, where these become the defaults. Our clients only use the
    # client credentials grant, so most of these guard flows we don't offer;
    # TOKEN_STORAGE keeps only a hash of each token in the database.
    "COMPLIANT_BCP_RFC9700_IMPLICIT_GRANT": True,
    "COMPLIANT_BCP_RFC9700_PASSWORD_GRANT": True,
    "COMPLIANT_BCP_RFC9700_PKCE_METHOD": True,
    "COMPLIANT_BCP_RFC9700_ACCESS_TOKEN_TRANSPORT": True,
    "COMPLIANT_BCP_RFC9700_AUTHZ_RESPONSE_ISS": True,
    "COMPLIANT_BCP_RFC9700_TOKEN_STORAGE": True,
    "COMPLIANT_BCP_RFC9700_REFRESH_TOKEN": True,
    "COMPLIANT_BCP_RFC9700_REDIRECT_URI_SCHEME": True,
    "COMPLIANT_BCP_RFC9700_REDIRECT_URI_MATCHING": True,
    "COMPLIANT_BCP_RFC9700_PKCE_REQUIRED": True,
    "REFRESH_TOKEN_REUSE_PROTECTION": True,
    "ALLOWED_REDIRECT_URI_SCHEMES": ["https"],
}
# The toolkit's own models, named so migrations can point at them (they're
# "swappable"; we don't swap them).
OAUTH2_PROVIDER_APPLICATION_MODEL = "oauth2_provider.Application"
# Requests per client (ninja's throttling, on the cache).
API_RATE_LIMIT = "600/m"

# Retention (privacy.retention, DATA_MODEL.md §16 phase 4). An account is
# deleted (a champion's or mentor's cleaned) this long after its last login,
# with reminder mails this many days before, and never sooner than
# ACCOUNT_DELETION_NOTICE_DAYS after the first reminder. Audit log entries
# with no account behind them go this long after they were written.
ACCOUNT_RETENTION_DAYS = 730
ACCOUNT_DELETION_REMINDER_DAYS = (30, 7)
ACCOUNT_DELETION_NOTICE_DAYS = 30
AUDIT_LOG_RETENTION_DAYS = 730
