"""
Django settings for website project.

Generated by 'django-admin startproject' using Django 3.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path
import environ

env = environ.Env(
    DEBUG=(bool, False),
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

environ.Env.read_env(BASE_DIR / ".env")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG", default=False)

ALLOWED_HOSTS = env.list("ALLOWED_HOSTS")

CSRF_TRUSTED_ORIGINS = env.list("CSRF_TRUSTED_ORIGINS")

# Set by the .devcontainer workspace (COOKIE_DOMAIN env var) so session/CSRF
# cookies scope correctly to coolregistration.localhost behind the nginx
# proxy; unset (None) for plain host-based `runserver` dev, which is fine.
COOKIE_DOMAIN = env('COOKIE_DOMAIN')
SESSION_COOKIE_DOMAIN = COOKIE_DOMAIN
CSRF_COOKIE_DOMAIN = COOKIE_DOMAIN

INTERNAL_IPS = [
    '127.0.0.1',
]

# Show the Debug Toolbar whenever Django's effective DEBUG setting is true.
# Reading django.conf.settings here is intentional: test overrides such as
# override_settings(DEBUG=False) should be respected by the callback.
def _show_debug_toolbar(request):
    from django.conf import settings
    return settings.DEBUG

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': _show_debug_toolbar,
}


AUTH_USER_MODEL = 'accounts.User'
LOGIN_URL = 'login'

AUTHENTICATION_BACKENDS = [
    'accounts.backends.EmailOrUsernameBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Account-approval invite emails (see applications.admin). Inside the
# .devcontainer workspace, EMAIL_HOST is set and mail goes to a Mailtrap
# sandbox inbox (see .devcontainer/docker-compose.yml); outside it (plain
# host-based `runserver`), EMAIL_HOST is unset and mail prints to the console.
EMAIL_HOST = env('EMAIL_HOST')
if EMAIL_HOST:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_PORT = env('EMAIL_PORT', default=2525)
    EMAIL_HOST_USER = env('EMAIL_HOST_USER')
    EMAIL_HOST_PASSWORD = env('EMAIL_HOST_PASSWORD')
    EMAIL_USE_TLS = env('EMAIL_USE_TLS', default=True)
else:
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

DEFAULT_FROM_EMAIL = env(
    'DEFAULT_FROM_EMAIL', default='CoderDojo Belgium <no-reply@coderdojobelgium.example>'
)

# Celery Configuration Options
CELERY_TIMEZONE = "Europe/Brussels"
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60

CELERY_RESULT_BACKEND = 'django-db'
CELERY_CACHE_BACKEND = 'default'

CELERY_BROKER_URL = f"redis://{ env('REDIS_HOST', default='127.0.0.1') }:{ env('REDIS_PORT', default='6379') }/0"

# Application definition

INSTALLED_APPS = [
    # Must be first — this is what makes `manage.py runserver` transparently
    # serve over ASGI (via Daphne) instead of the default WSGI dev server,
    # which is what lets notifications/consumers.py's WebSocket route work
    # with zero changes to how the devcontainer/docs already invoke runserver.
    'daphne',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    "django.contrib.gis",
    "debug_toolbar",
    'core',
    'geo',
    'accounts',
    'dojos',
    'pathways',
    'events',
    'content',
    'applications',
    'notifications',
    'django_celery_results',
    'mailing'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    # Must come after SessionMiddleware, before CommonMiddleware, per
    # https://docs.djangoproject.com/en/6.1/topics/i18n/translation/#how-django-discovers-language-preference
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'accounts.middleware.ForcePasswordChangeMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'website.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'accounts.context_processors.user_roles',
            ],
        },
    },
]

WSGI_APPLICATION = 'website.wsgi.application'
# What `daphne` (see INSTALLED_APPS) actually serves `runserver` through —
# website/asgi.py routes plain HTTP requests through Django as usual and
# WebSocket connections (notifications/routing.py) through Channels.
# WSGI_APPLICATION is left in place for any WSGI-only tooling; it's not
# what's actually handling requests once daphne is installed.
ASGI_APPLICATION = 'website.asgi.application'


# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases
#
# Defaults below match the standalone host-side MySQL container used before
# the .devcontainer setup existed:
# docker run --name mysql-coderdojo   -e MYSQL_DATABASE=coderdojo   -e MYSQL_USER=coderdojo   -e MYSQL_PASSWORD=coderdojo   -e MYSQL_ROOT_PASSWORD=rootpassword   -p 13306:3306   -d mysql
# Inside the .devcontainer workspace, DB_* env vars (see docker-compose.yml)
# point this at the `db` service instead.

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.mysql',
        'NAME': env('DB_NAME', default='coderdojo'),
        'USER': env('DB_USER', default='coderdojo'),
        'PASSWORD': env('DB_PASSWORD', default='coderdojo'),
        'HOST': env('DB_HOST', default='127.0.0.1'),
        'PORT': env('DB_PORT', default='13306'),
    }
}

# Cache / Redis. Inside the .devcontainer workspace, REDIS_HOST points at
# the `redis` service; outside it, this falls back to a local Redis on the
# default port (or just won't connect until one exists — the cache is not
# required for the app to boot).
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': 'redis://{host}:{port}/0'.format(
            host= env('REDIS_HOST', default='127.0.0.1'),
            port= env('REDIS_PORT', default='6379'),
        ),
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
            # Cache reads/writes fail open rather than raising — without a
            # local Redis (e.g. host-based dev/tests outside the
            # devcontainer, where REDIS_HOST defaults to 127.0.0.1 with
            # nothing listening), every cache.get()/set() would otherwise
            # hard-error instead of just skipping the cache.
            'IGNORE_EXCEPTIONS': True,
            'SOCKET_CONNECT_TIMEOUT': 2,
            'SOCKET_TIMEOUT': 2,
        },
    }
}

# Channels' backing store for notifications/consumers.py — same Redis
# instance as CACHES above (same REDIS_HOST/REDIS_PORT), but db 1 rather
# than 0 so channel-layer keys never collide with cache keys. Unlike the
# cache, there's no IGNORE_EXCEPTIONS-style fail-open option here: without
# Redis, group_send() in notifications.services.notify() will raise, which
# is caught there rather than here (a live push failing shouldn't break
# the action that triggered the notification; the DB row is what matters).
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [('redis://{host}:{port}/1'.format(
                host=env('REDIS_HOST', default='127.0.0.1'),
                port=env('REDIS_PORT', default='6379'),
            ))],
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

# Offered in the menu's language switcher (django.views.i18n.set_language,
# see website/urls.py). No page content is translated into these yet — this
# wires the real, working switching mechanism (session-stored locale,
# LocaleMiddleware) as a first step; actual .po translation catalogs for
# nl-be/fr-be/de are a separate follow-up.
LANGUAGES = [
    ('en-us', 'English'),
    ('nl-be', 'Nederlands (België)'),
    ('fr-be', 'Français (Belgique)'),
    ('de', 'Deutsch'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static"
]

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Background check documents (criminal record extracts) are sensitive and
# must never be reachable via a public URL, unlike MEDIA_ROOT above which
# website/urls.py serves directly under DEBUG. This directory has no
# corresponding url() — the only way to read a file here is through the
# permission-gated view in applications.views. See applications.storage.
PRIVATE_MEDIA_ROOT = BASE_DIR / "private_media"

