# Generated by Django 6.1.1 on 2026-09-24 10:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dojos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('url', models.CharField(blank=True, default='', max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read', models.BooleanField(default=False)),
                ('dojo', models.ForeignKey(blank=True, help_text="The dojo this notification concerns, if any — lets a multi-dojo owner's admin panel (dojos.views._notification_context) show only the dojo currently being managed. Read state stays per-recipient regardless (see `read` below): a dojo-level event that concerns more than one person fans out to one row per recipient, sharing the same dojo/text/url but each with its own independent read flag — see notifications.services.notify.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dojos.dojo')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
