# Generated by Django 6.1.1 on 2026-09-23 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dojos', '0007_alter_mentor_owner_account_alter_mentor_role'),
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='dojo',
            field=models.ForeignKey(blank=True, help_text="The dojo this notification concerns, if any — lets a multi-dojo owner's admin panel (dojos.views._notification_context) show only the dojo currently being managed. Read state stays per-recipient regardless (see `read` below): a dojo-level event that concerns more than one person fans out to one row per recipient, sharing the same dojo/text/url but each with its own independent read flag — see notifications.services.notify.", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='dojos.dojo'),
        ),
    ]
