# Generated by Django 6.1.1 on 2026-09-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="organisation",
            field=models.BooleanField(
                default=False,
                help_text="For the organisation dashboard's bell (DATA_MODEL.md §23), e.g. someone opened access to the Django admin. Personal notices without a dojo leave it off.",
            ),
        ),
    ]
